TIPS = [
    {
        "id": 1,
        "title": "dags describe the pipeline",
        "definition": "A DAG — directed acyclic graph — is the pipeline definition: tasks as nodes and dependencies as edges, declared in a Python file the scheduler parses. The @dag decorator wraps a function whose body wires tasks together, and each file produces DAGs that Airflow runs on a schedule.",
        "example": "from airflow.decorators import dag, task\nfrom datetime import datetime\n\n@dag(schedule='@daily', start_date=datetime(2026, 1, 1), catchup=False)\ndef daily_report():\n    ...\n\ndaily_report()",
        "usecase": "Encoding entire pipelines as readable Python rather than configuration formats.",
        "category": "airflow",
    },
    {
        "id": 2,
        "title": "tasks are the work units",
        "definition": "A task is one executable step inside a DAG — a Python function under @task or an operator instance — and each runs independently with its own logs, retries and outcome. The DAG's graph is built from task objects, and execution is simply running each task in dependency order.",
        "example": "@task\ndef normalize(df):\n    return df.fillna(0)\n\n@task\ndef load(clean):\n    warehouse.write(clean)",
        "usecase": "Breaking pipelines into steps that fail, retry and be observed alone.",
        "category": "airflow",
    },
    {
        "id": 3,
        "title": "operators call the world",
        "definition": "Operators are ready-made task types for a tool: BashOperator runs shell commands, PythonOperator calls a function, and provider packages ship thousands more — PostgresOperator, S3ToRedshiftOperator and so on. Choosing the right operator keeps the step's intent and credentials packaged correctly.",
        "example": "from airflow.operators.bash import BashOperator\n\ncheck = BashOperator(\n    task_id='verify_disk',\n    bash_command='df -h /data | tail -1',\n)",
        "usecase": "Reaching external systems with battle-tested glue instead of custom scripts.",
        "category": "airflow",
    },
    {
        "id": 4,
        "title": "dependencies order the flow",
        "definition": "The >> and << operators wire task order: a >> b means b waits for a, and a graph is assembled from chains, lists and branches. Dependencies are the only way the scheduler knows what can run in parallel — every edge is a wait condition.",
        "example": "fetch >> clean >> [analyze, backup]\nanalyze >> report\nbackup >> report",
        "usecase": "Declaring parallel lanes and merge points purely with arrows.",
        "category": "airflow",
    },
    {
        "id": 5,
        "title": "the scheduler drives everything",
        "definition": "The scheduler is the always-on process that parses DAG files, decides which task instances are due and hands them to the executor. It runs its own loops and does the orchestration — schedules, retries and dependencies — while the webserver and workers handle the rest.",
        "example": "# terminal\nairflow scheduler",
        "usecase": "The long-running brain every real deployment keeps alive.",
        "category": "airflow",
    },
    {
        "id": 6,
        "title": "schedules set the cadence",
        "definition": "The schedule argument tells Airflow when to create DagRuns — cron-like strings, presets like '@daily', or timedelta intervals. A run is created when the schedule passes, so the calendar on which pipelines fire is one declarative setting per DAG.",
        "example": "@dag(schedule='30 6 * * 1-5', start_date=datetime(2026, 1, 1))\ndef morning_report():\n    ...",
        "usecase": "Running pipelines at calendar or clock moments, not by hand.",
        "category": "airflow",
    },
    {
        "id": 7,
        "title": "catchup fills the gaps",
        "definition": "By default Airflow backfills every missed schedule interval between start_date and now. catchup=False skips the backlog and starts fresh, which is what most teams want after fixing a broken DAG or adding a new one — otherwise an old start_date spawns a swarm of runs.",
        "example": "@dag(schedule='@hourly', start_date=datetime(2025, 6, 1),\n     catchup=False)\ndef sensor_sync():\n    ...",
        "usecase": "New DAGs and repaired pipelines that should not replay ancient history.",
        "category": "airflow",
    },
    {
        "id": 8,
        "title": "params customize the run",
        "definition": "dag_run.conf carries per-run input — triggered manually with a JSON payload or set inside other tasks — and params provides the defaults the UI and code share. Reads at task runtime make each execution instance configurable without editing the DAG file.",
        "example": "@task\ndef key_customer(dag_run, params=None):\n    segment = params.get('segment', 'standard') if params else 'standard'\n    return Revenue.by_segment(segment)",
        "usecase": "Ad-hoc manual runs, backfills and customer-specific executions.",
        "category": "airflow",
    },
    {
        "id": 9,
        "title": "xcom passes small data",
        "definition": "XComs are key-value messages tasks push and pull — a task's return value is stored automatically, and the task instance context pulls it downstream. Designed for small metadata like file paths or row counts, not bulk data; large payloads belong in storage, not the metadata database.",
        "example": "@task\ndef write_file():\n    return '/tmp/export.csv'     # pushed as xcom\n\n@task\ndef load(path=None):\n    warehouse.copy_from(path)",
        "usecase": "Passing file names, ids and small parameters between steps.",
        "category": "airflow",
    },
    {
        "id": 10,
        "title": "task instances track the run",
        "definition": "Each time a task runs it becomes a TaskInstance with its own state — queued, running, success, failed — plus attempt numbers, start and end times. The UI, logs and code all address these instances, which is how retries and runs stay distinguishable in history.",
        "example": "@task\ndef write_log(self, **context):\n    ti = context['ti']\n    log(f'run {ti.dag_run.run_id} attempt {ti.try_number}')",
        "usecase": "Attributing behavior to a precise run and attempt in logs and metrics.",
        "category": "airflow",
    },
    {
        "id": 11,
        "title": "retries heal flaky steps",
        "definition": "Retries are built into task definitions: retries=N and retry_delay=timedelta re-run a failed step automatically, and retry_exponential_backoff paces the attempts. Transient failures — timeouts, connection resets — resolve themselves without human paging.",
        "example": "from datetime import timedelta\n\n@task(retries=4, retry_delay=timedelta(minutes=2),\n      retry_exponential_backoff=True)\ndef poll_api():\n    reviews = api.fetch()",
        "usecase": "Steps against flaky networks and third-party APIs.",
        "category": "airflow",
    },
    {
        "id": 12,
        "title": "webserver shows the progress",
        "definition": "The webserver serves the Airflow UI: the grid of DAGs, tree views, task logs, run states, triggers and code. It is the operations surface where engineers watch, restart and investigate runs — plus the trigger-with-config form for manual execution.",
        "example": "# terminal\nairflow webserver -p 8080",
        "usecase": "Day-to-day operations: what ran, when, and why it failed.",
        "category": "airflow",
    },
    {
        "id": 13,
        "title": "sensors wait for conditions",
        "definition": "Sensors are tasks that pause until a condition holds — a file appears, an API reports success, another pipeline finishes — checking repeatedly until timeout. They turn external events into schedule-independent pipeline starts.",
        "example": "from airflow.sensors.filesystem import FileSensor\n\nwait = FileSensor(\n    task_id='wait_for_drop',\n    filepath='/data/inputs/latest.csv',\n    timeout=3600,\n)",
        "usecase": "Waiting on external deliveries before processing begins.",
        "category": "airflow",
    },
    {
        "id": 14,
        "title": "timeouts keep steps in check",
        "definition": "execution_timeout bounds a task's total run time, after which Airflow kills it and marks the step failed rather than letting a hang occupy a slot. Setting it per task — generous for batches, tight for polls — converts runaway waits into loud failures.",
        "example": "@task(execution_timeout=timedelta(minutes=30))\ndef heavy_transform():\n    dbt.run()",
        "usecase": "Guarding against hangs in workers and external systems.",
        "category": "airflow",
    },
    {
        "id": 15,
        "title": "branches split the path",
        "definition": "BranchPythonOperator runs a function whose job is choosing which downstream tasks to follow; the discarded tasks show as skipped in the UI. Branching composes with other tasks, and appending a common downstream keeps every branch re-converging.",
        "example": "from airflow.operators.python import BranchPythonOperator\n\ndef choose():\n    return 'load' if VALIDATION_OK else 'alert'\n\nbranch = BranchPythonOperator(task_id='branch', python_callable=choose)",
        "usecase": "Conditional flows — success paths, fallbacks and early exits.",
        "category": "airflow",
    },
    {
        "id": 16,
        "title": "task groups organize the graph",
        "definition": "TaskGroup wraps a set of tasks under one collapsible node, keeping wide DAG graphs readable while the tasks inside still run normally. Grouping repeated sub-pipelines — ingest, transform, publish — turns a tangled graph into a layered diagram.",
        "example": "from airflow.utils.task_group import TaskGroup\n\nwith TaskGroup('ingest') as ingest:\n    pull = PullOperator(task_id='pull')\n    validate = ValidateOperator(task_id='validate')\n    pull >> validate",
        "usecase": "Keeping large graphs navigable in the UI and code.",
        "category": "airflow",
    },
    {
        "id": 17,
        "title": "dynamic mappings scale the work",
        "definition": "Dynamic task mapping expands one task into many parallel instances at runtime: partial() with input lists creates an instance per element, all running the same code on different data. Fan-out for variable-sized batches needs no static, design-time enumeration.",
        "example": "@task\ndef fetch_region(region):\n    return api.by_region(region)\n\nregions = ['east', 'west', 'south']\nresults = fetch_region.expand(region=regions)",
        "usecase": "Processing N customers, files or regions without editing the DAG per batch.",
        "category": "airflow",
    },
    {
        "id": 18,
        "title": "dags files stay light",
        "definition": "DAG files are parsed every few seconds by the scheduler, so they should import fast and define structure only. Heavy work — calculations, moving data — belongs inside tasks; a slow import slows the whole scheduler parse loop across every DAG in the fleet.",
        "example": "# bad: heavy work at import time\ndata = download_big_catalog()   # runs on every scheduler parse\n\n# good: the DAG file only wires tasks together",
        "usecase": "Keeping scheduler parse latency low as DAG counts grow.",
        "category": "airflow",
    },
    {
        "id": 19,
        "title": "datasets trigger across dags",
        "definition": "Datasets let one DAG's output trigger another by listening for a dataset rather than a clock: schedules point at datasets, and producing the dataset fires the consumer's runs. Cross-DAG dependencies become data-driven instead of fragile timing guesses.",
        "example": "@dag(schedule='0 6 * * *')\ndef nightly_ingest():\n    publish(data_sets.raw_orders)\n\n@dag(schedule=[data_sets.raw_orders], catchup=False)\ndef downstream_report():\n    ...",
        "usecase": "Chaining pipelines that must run in data order, not wall-clock order.",
        "category": "airflow",
    },
    {
        "id": 20,
        "title": "providers bring integrations",
        "definition": "Provider packages ship operators, sensors, hooks and transfers for each system — apache-airflow-providers-postgres, -amazon, -kubernetes and hundreds more. Installing the provider brings maintained glue, so edge connectors come from the ecosystem instead of bespoke code.",
        "example": "# terminal\npip install apache-airflow-providers-postgres \\\n    apache-airflow-providers-amazon",
        "usecase": "Standard connectors for the systems your data already touches.",
        "category": "airflow",
    },
    {
        "id": 21,
        "title": "variables store the config",
        "definition": "Variable.get(name) reads key-value settings from the metadata database, editable via UI or CLI without redeploying DAG files. Queried at task runtime — not import time — they let configuration change without code deploys or scheduler restarts.",
        "example": "from airflow.models import Variable\n\n@task\ndef load_threshold():\n    threshold = Variable.get('load_threshold', default_var=0.8)",
        "usecase": "Tuning knobs and environment differences handled at runtime.",
        "category": "airflow",
    },
    {
        "id": 22,
        "title": "connections hold the credentials",
        "definition": "Connections centralize how DAGs reach external systems: host, port, login, password and extras stored under a conn id and fetched in tasks. Code references conn_id only, so credentials live outside the DAG files and rotate through UI, CLI or environment alone.",
        "example": "from airflow.hooks.postgres_hook import PostgresHook\n\n@task\ndef query_warehouse():\n    hook = PostgresHook(postgres_conn_id='warehouse_ro')\n    rows = hook.get_records('select count(*) from orders')",
        "usecase": "Keeping passwords and hosts out of version-controlled DAG files.",
        "category": "airflow",
    },
    {
        "id": 23,
        "title": "secrets backends hide the keys",
        "definition": "Connections and variables can resolve from a secrets backend — Vault, AWS Secrets Manager, GCP Secrets — instead of plaintext in the metadata database. Airflow fetches them lazily at runtime, so secret material never sits in the database or the DAG file.",
        "example": "# airflow.cfg\n[secrets]\nbackend = airflow.providers.hashicorp.secrets.vault.VaultBackend\nbackend_kwargs = {\"mount_point\": \"airflow\", \"url\": \"http://vault:8200\"}",
        "usecase": "Compliance-friendly secret handling at fleet scale.",
        "category": "airflow",
    },
    {
        "id": 24,
        "title": "pools cap the concurrency",
        "definition": "Pools limit how many tasks of selected names run at once: define a pool with N slots and attach pool= to tasks, and the scheduler holds the rest queued. They protect external systems — a database that can handle five parallel loads — from DAG-shaped bursts.",
        "example": "from airflow.models import Pool\n\nPool.get_or_create('warehouse_loads', slots=5)\n\n@task(pool='warehouse_loads')\ndef load_orders():\n    ...",
        "usecase": "Constraining load on shared backends without serializing whole DAGs.",
        "category": "airflow",
    },
    {
        "id": 25,
        "title": "queues route to workers",
        "definition": "Every task can name a queue; a worker consumes only the queues it is started with. Dedicating queues — GPU jobs, heavy ETL, interactive — keeps heterogeneous workers busy with work they can actually run.",
        "example": "@task(queue='gpu')\ndef train_model():\n    trainer.fit()\n\n# terminal on the GPU worker\nairflow worker --queues=gpu",
        "usecase": "Mixed fleets where some workers have capabilities others lack.",
        "category": "airflow",
    },
    {
        "id": 26,
        "title": "priority balances the demand",
        "definition": "priority_weight orders queued tasks within a pool — the scheduler runs higher-weight tasks first when slots are contended. Low-priority housekeeping and high-priority customer jobs coexist with full queues through weights alone.",
        "example": "@task(pool='default', priority_weight=20)\ndef sync_critical():\n    ...\n\n@task(pool='default', priority_weight=1)\ndef cleanup_old():\n    ...",
        "usecase": "Fairness decisions when demand exceeds pool slots.",
        "category": "airflow",
    },
    {
        "id": 27,
        "title": "executors define the parallel",
        "definition": "The executor is how the scheduler hands tasks to workers: SequentialExecutor runs one at a time, LocalExecutor forks the same machine, CeleryExecutor spreads across a cluster and KubernetesExecutor schedules pods. The same DAG code runs under any of them — scale is infrastructure, not DAG rewrites.",
        "example": "# airflow.cfg\n[core]\nexecutor = CeleryExecutor",
        "usecase": "Growing from a laptop to a cluster by changing configuration.",
        "category": "airflow",
    },
    {
        "id": 28,
        "title": "standalone boots a local stack",
        "definition": "airflow standalone starts the full local stack — metadata DB, scheduler, webserver and worker — on one machine, the fastest way to try Airflow. It runs the SequentialExecutor and writes a default admin password to the console for the first login.",
        "example": "# terminal\nairflow standalone",
        "usecase": "Local exploration and demos without deployment work.",
        "category": "airflow",
    },
    {
        "id": 29,
        "title": "cli drives the dags",
        "definition": "The CLI mirrors the UI for automation: airflow dags list, airflow dags trigger with a conf payload, airflow dags backfill, and airflow tasks list. Scripts, CI checks and cron jobs drive pipelines through these stable commands.",
        "example": "# terminal\nairflow dags trigger --conf '{\"region\": \"us-east\"}' sales_pipeline\nairflow dags list",
        "usecase": "Triggering and inspecting pipelines from scripts and CI.",
        "category": "airflow",
    },
    {
        "id": 30,
        "title": "task test runs one step",
        "definition": "airflow tasks test dag_id task_id <date> runs a single task locally without the scheduler, executing its current logic against the metadata database. It is the fastest feedback loop after editing a task — one command instead of a full triggered run.",
        "example": "# terminal\nairflow tasks test sales_pipeline compute_metrics 2026-01-15",
        "usecase": "Debugging a step's logic and inputs in isolation.",
        "category": "airflow",
    },
    {
        "id": 31,
        "title": "dag factory reuses the shape",
        "definition": "A function that returns DAGs — configured per call by name, schedule and params — lets one code shape produce many similar pipelines. Teams with parallel flows for regions or brands maintain one template instead of dozens of near-identical files.",
        "example": "def make_dag(region, table):\n    @dag(dag_id=f'sync_{region}', schedule='0 * * * *', catchup=False)\n    def sync():\n        ...\n    return sync()\n\nfor r in ['us', 'eu', 'ap']:\n    globals()[f'sync_{r}'] = make_dag(r, f'users_{r}')",
        "usecase": "Multi-region and multi-tenant pipelines from one DAG template.",
        "category": "airflow",
    },
    {
        "id": 32,
        "title": "tests import the dags",
        "definition": "DAGs are testable Python: import the file through a dag bag, assert task counts and dependency edges, and lint that operators configure required fields. pytest plus the Airflow test helpers turns pipeline structure into a regression-checked contract.",
        "example": "# test_dags.py\nfrom airflow.models import DagBag\n\ndef test_dag_loads():\n    bag = DagBag(dag_folder='dags/', include_examples=False)\n    assert 'sales_pipeline' in bag.dags\n\ndef test_task_count():\n    dag = DagBag().dags['sales_pipeline']\n    assert len(dag.tasks) == 7",
        "usecase": "Catching broken DAGs in CI before the scheduler ever parses them.",
        "category": "airflow",
    },
    {
        "id": 33,
        "title": "imports stay side-effect free",
        "definition": "The scheduler imports DAG files repeatedly and impersonally: top-level code that queries databases, reads files or waits on the network runs on every parse and can hang or fail the whole file. All I/O belongs inside tasks, leaving the import path pure structure.",
        "example": "# bad: side effects at import\nconn = get_database_conn()      # runs on every scheduler parse\n\n# good: open the connection inside the task\n@task\ndef load():\n    with get_database_conn() as c:\n        ...",
        "usecase": "Stable parsing under frequent scheduler re-imports.",
        "category": "airflow",
    },
    {
        "id": 34,
        "title": "callbacks notify the events",
        "definition": "on_success_callback, on_failure_callback and on_retry_callback attach handlers to task lifecycle events, each receiving the task instance context. Teams wire Slack, email and metrics emission here — a single decorator keeps pipelines noisy about their own fate.",
        "example": "def notify_failure(context):\n    slack.send('task %s failed' % context['task_instance'].task_id)\n\n@task(on_failure_callback=notify_failure)\ndef fragile_step():\n    ...",
        "usecase": "Central alerting without threading notification logic through tasks.",
        "category": "airflow",
    },
    {
        "id": 35,
        "title": "retry callbacks flag the trouble",
        "definition": "on_retry_callback fires each time a task is about to retry, so flaky-but-recovering work is visible rather than silent. Together with plain retry settings, it draws the line between transient blips and truly failed runs in the operations timeline.",
        "example": "def warn_retry(context):\n    metrics.increment('task.retry')\n\n@task(retries=3, on_retry_callback=warn_retry)\ndef flaky():\n    ...",
        "usecase": "Tracking retry storms and flaky steps before they become incidents.",
        "category": "airflow",
    },
    {
        "id": 36,
        "title": "sla misses keep their promise",
        "definition": "Tasks can declare an SLA — a deadline for completion — and a miss triggers sla_miss_callback with the details of what blocked. SLAs turn silent lateness into measured promise-keeping instead of post-hoc blame.",
        "example": "def on_sla_miss(dag, task_list, blocking_task_list, **kwargs):\n    alert('SLA missed by %s' % ', '.join(t.task_id for t in task_list))\n\n@task(sla=timedelta(hours=2))\ndef morning_load():\n    ...",
        "usecase": "Contractual timeliness for onboarding and reporting pipelines.",
        "category": "airflow",
    },
    {
        "id": 37,
        "title": "backfill runs past dates",
        "definition": "airflow dags backfill dag_id -s <start> -e <end> executes every scheduled interval in a range as if the clock had arrived. Repairing a broken historical period or seeding a new dataset replays logic forward over real event time.",
        "example": "# terminal\nairflow dags backfill nightly_stats -s 2026-01-01 -e 2026-01-10",
        "usecase": "Reprocessing ranges of historical runs after logic or data fixes.",
        "category": "airflow",
    },
    {
        "id": 38,
        "title": "max_active_runs prevents overlap",
        "definition": "max_active_runs caps how many DagRuns of one DAG run simultaneously — overlapping runs are allowed by default, which busy schedules will hit. For pipelines that recalculate the same tables, bound it to 1 so runs serialize instead of racing.",
        "example": "@dag(schedule='*/30 * * * *', max_active_runs=1)\ndef upsert_batch():\n    ...",
        "usecase": "Schedules faster than the run itself — long batches without pile-ups.",
        "category": "airflow",
    },
    {
        "id": 39,
        "title": "depends_on_past connects runs",
        "definition": "depends_on_past=True makes a task wait until the previous run's same task succeeded — a chain across run history. Combined with max_active_runs=1 it serializes executions into strict orderings where no run overtakes its predecessor.",
        "example": "@task(depends_on_past=True)\ndef incremental_build():\n    ...",
        "usecase": "Stateful pipelines where each run builds on the previous run's output.",
        "category": "airflow",
    },
    {
        "id": 40,
        "title": "paused dags stay dormant",
        "definition": "A paused DAG stops scheduling: no new DagRuns, existing runs finish, and the graph stays in the UI for inspection. Pausing — not deleting — is the off switch for experiments and broken pipelines, keeping history while stopping execution.",
        "example": "# terminal\nairflow dags pause broken_experiment",
        "usecase": "Quieting work without losing definitions or run history.",
        "category": "airflow",
    },
    {
        "id": 41,
        "title": "notifications reach the humans",
        "definition": "Email notifications on task failure or success work once the SMTP settings are configured, and plugins extend alerts to Slack, Teams and PagerDuty. Alerting is part of the pipeline contract: no silent failures.",
        "example": "# airflow.cfg\n[email]\nemail_backend = airflow.utils.email.send_email_smtp\nsmtp_host = smtp.example.com\nsmtp_starttls = True",
        "usecase": "Human eyes on failures even when dashboards are dark.",
        "category": "airflow",
    },
    {
        "id": 42,
        "title": "logs live per task run",
        "definition": "Every task instance has its own log stream — remote logging can send it to S3, GCS or a file system — grouped by run and attempt. The UI serves log viewers directly, so debugging goes from a run id to the relevant log lines in one click.",
        "example": "# terminal\nairflow tasks logs dag_id task_id 2026-01-15 --try-number 2",
        "usecase": "Tracing the exact attempt's output during post-mortems.",
        "category": "airflow",
    },
    {
        "id": 43,
        "title": "taskflow keeps it in python",
        "definition": "The TaskFlow API (@dag and @task) replaces traditional operators with plain Python functions, passing return values between tasks implicitly via xcom. Pipelines read like code — feed one task's output into the next function — instead of an operator zoo.",
        "example": "@task\ndef fetch():\n    return raw_rows\n\n@task\ndef transform(data):\n    return clean(data)\n\n@dag(schedule='@hourly')\ndef etl():\n    transform(fetch())\n\netl()",
        "usecase": "Readable pipelines where data flow mirrors the code's structure.",
        "category": "airflow",
    },
    {
        "id": 44,
        "title": "docker isolates the step",
        "definition": "DockerOperator runs a task inside a container from any image — pinned versions, exotic toolchains, isolated dependencies — with volumes and environment wired in. Steps with heavy or conflicting requirements execute exactly as their image dictates.",
        "example": "from airflow.providers.docker.operators.docker import DockerOperator\n\nrender = DockerOperator(\n    task_id='render_pdf',\n    image='reports/pdftool:2.3',\n    command='render --input /tmp/in.csv --output /tmp/out.pdf',\n    mount_tmp_dir=True,\n)",
        "usecase": "Legacy tools and pinned environments inside a modern DAG.",
        "category": "airflow",
    },
    {
        "id": 45,
        "title": "dag runs keep history",
        "definition": "Every executed interval becomes a DagRun with its own state and run id, keeping a full audit trail from creation to success or failure. The run history is where backfills, manual triggers and scheduled runs are distinguished — and where accountability lives.",
        "example": "# terminal\nairflow dags report\nairflow dags list-runs -d sales_pipeline",
        "usecase": "Auditing what ran when, and differentiating manual from scheduled.",
        "category": "airflow",
    },
    {
        "id": 46,
        "title": "doc_md documents the dag",
        "definition": "doc_md on the DAG renders as its documentation page in the UI — ownership, purpose, schedule rationale, run book pointers. Inline documentation converts a year-old DAG from mystery into handover material.",
        "example": "@dag(\n    schedule='@daily',\n    doc_md='''\n        ### Sales sync\n        Owned by data-eng. Depends on the ERP drop landing in s3://raw/.\n        Contact data-eng@example.com on failures.\n    ''',\n)\ndef sales_sync():\n    ...",
        "usecase": "Tribal knowledge codified where operators actually look.",
        "category": "airflow",
    },
    {
        "id": 47,
        "title": "dags need unique ids",
        "definition": "dag_id must be globally unique — the scheduler dedupes by it, and two DAGs sharing an id fight over runs and metadata. Automatic ids are possible but must stay deterministic, or restarts create duplicate identities for the same work.",
        "example": "@dag(dag_id='ingest_orders_weekly', schedule='0 1 * * 1')\ndef orders_weekly():\n    ...",
        "usecase": "Stable, unique identities for every pipeline in the fleet.",
        "category": "airflow",
    },
    {
        "id": 48,
        "title": "restarts keep the stack alive",
        "definition": "Scheduler and webserver are long-running services the deployment must supervise — systemd, Docker or Kubernetes — restarting on crash while the metadata database stays safe. DAG definitions are re-parsed from files at restart, so deploys are a simple code push plus process bounce.",
        "example": "# systemd sketch\n[Unit]\nDescription=Airflow scheduler\n[Service]\nExecStart=airflow scheduler\nRestart=always",
        "usecase": "Service-level resilience for the components that run everything.",
        "category": "airflow",
    },
    {
        "id": 49,
        "title": "cross-dag triggers coordinate",
        "definition": "The ExternalTaskSensor waits for a task in another DAG, and TriggerDagRunOperator starts another DAG from within a task — the two primitives for cross-pipeline coordination. Together they nest pipelines or let one completion trigger the next.",
        "example": "from airflow.operators.trigger_dagrun import TriggerDagRunOperator\n\ntrigger = TriggerDagRunOperator(\n    task_id='kick_off_report',\n    trigger_dag_id='weekly_report',\n    wait_for_completion=True,\n)",
        "usecase": "Concerted multi-DAG flows driven by completion rather than crons.",
        "category": "airflow",
    },
    {
        "id": 50,
        "title": "one dag per file",
        "definition": "Holding one DAG per file is the convention the tooling assumes: the dag bag discovers by file name, the UI groups by file and debugging is a single-file exercise. Multiple DAGs in one file are legal but erode the discoverability and isolation pipelines rely on.",
        "example": "# dags/\n#   ingest_orders.py\n#   nightly_stats.py\n#   weekly_report.py\n# each file creates exactly one DAG object",
        "usecase": "Fleets where finding, testing and changing one pipeline stays trivial.",
        "category": "airflow",
    },
]