TIPS = [
    {
        "id": 1,
        "title": "async def marks the coroutine",
        "definition": "A function defined with async def becomes a coroutine function: calling it does not run anything, it returns a coroutine object that must be awaited to execute. The keyword communicates that the function suspends at await points and resumes later, shifting the whole program into the event loop's cooperative model.",
        "example": "async def fetch():\n    return 'data'\n\ncoro = fetch()          # nothing ran yet\nvalue = await coro      # now it runs",
        "usecase": "Every async API starts here — the syntax alone changes how calling and sequencing work.",
        "category": "asyncio",
    },
    {
        "id": 2,
        "title": "await hands control back",
        "definition": "The await expression suspends the current coroutine and hands control to the event loop until the awaited thing finishes, then resumes with its result. While suspended, other tasks run, so one slow await never blocks the others as long as the awaited operation itself stays non-blocking.",
        "example": "async def page():\n    html = await http_get('https://example.com')\n    return parse(html)",
        "usecase": "Expressing sequential dependencies — fetch then parse — while other tasks keep running between the steps.",
        "category": "asyncio",
    },
    {
        "id": 3,
        "title": "asyncio.run drives everything",
        "definition": "asyncio.run(coro) creates a fresh event loop, runs the coroutine to completion and closes the loop afterwards. It is the single entry point for scripts and tests: no manual loop management, no forgotten handlers keeping the process alive, and calling it again later starts a clean second run.",
        "example": "import asyncio\n\nasync def main():\n    data = await fetch_all()\n    print(len(data))\n\nasyncio.run(main())",
        "usecase": "Any async program's top level — from tiny scripts to CLI tools.",
        "category": "asyncio",
    },
    {
        "id": 4,
        "title": "a coroutine must be awaited",
        "definition": "Forgetting await leaves a coroutine object unstarted, and Python warns that it was never awaited when the object is garbage collected. The result is code that silently does nothing while the program continues; checking that every call site contains await fixes the classic first-week async bug.",
        "example": "async def slow():\n    await asyncio.sleep(1)\n    return 42\n\nasync def main():\n    value = slow()          # bug: missing await\n    print(value)            # prints <coroutine object...>",
        "usecase": "Catching silent no-op calls in code review and runtime warnings.",
        "category": "asyncio",
    },
    {
        "id": 5,
        "title": "tasks schedule concurrently",
        "definition": "asyncio.create_task(coro) schedules the coroutine to run independently on the loop and returns a Task handle immediately, so several tasks can be in flight at once. The event loop interleaves them at every await point, which is how concurrent IO happens without threads.",
        "example": "async def main():\n    t1 = asyncio.create_task(fetch('a'))\n    t2 = asyncio.create_task(fetch('b'))\n    r1, r2 = await t1, await t2",
        "usecase": "Kicking off several independent operations and awaiting them together.",
        "category": "asyncio",
    },
    {
        "id": 6,
        "title": "gather runs many at once",
        "definition": "asyncio.gather(*coros) runs all coroutines concurrently and returns their results in the order they were passed, waiting for every one unless told otherwise. It is the one-call concurrency primitive for homogeneous work — fetches, renders, writes — with results collected in matching order.",
        "example": "results = await asyncio.gather(\n    fetch('https://site-a.com'),\n    fetch('https://site-b.com'),\n    fetch('https://site-c.com'),\n)",
        "usecase": "Fanning out any batch of identical calls and receiving the answers positionally.",
        "category": "asyncio",
    },
    {
        "id": 7,
        "title": "return_exceptions keeps gather going",
        "definition": "By default gather propagates the first exception and, importantly, the other tasks keep running while the await point raises. With return_exceptions=True, gather never raises: each failing task's exception is returned in its place in the results list, letting callers decide what counts as fatal.",
        "example": "results = await asyncio.gather(*jobs, return_exceptions=True)\nfor name, outcome in zip(names, results):\n    if isinstance(outcome, Exception):\n        log.warning('%s failed', name)",
        "usecase": "Batch processing where one failure should not mask the others' outcomes.",
        "category": "asyncio",
    },
    {
        "id": 8,
        "title": "wait_for sets a deadline",
        "definition": "asyncio.wait_for(coro, timeout) runs a coroutine under a hard deadline and raises TimeoutError when the bound passes; the timed-out coroutine is cancelled so nothing dangles. Combining wait_for with gather gives whole-batch deadlines, and a timeout of None means no bound at all.",
        "example": "try:\n    data = await asyncio.wait_for(fetch(), timeout=5)\nexcept TimeoutError:\n    data = CACHE['fallback']",
        "usecase": "External calls that must fail fast — APIs, DNS, sockets — instead of hanging a worker.",
        "category": "asyncio",
    },
    {
        "id": 9,
        "title": "timeout gives a time window",
        "definition": "asyncio.timeout(seconds), new in Python 3.11, wraps a block as a context manager that raises TimeoutError when the window closes. Unlike wait_for it raises from inside the block, so partially completed work can run cleanup, and it can also be awaited as a standalone primitive.",
        "example": "async with asyncio.timeout(5):\n    data = await fetch()\n    parse(data)",
        "usecase": "Scoped deadlines that let the inner code react to running out of time.",
        "category": "asyncio",
    },
    {
        "id": 10,
        "title": "sleep lets others run",
        "definition": "await asyncio.sleep(0) yields control to the loop without waiting at all, letting other ready tasks make progress — the cooperative scheduler's way of saying the current turn is done. Real delays use sleep with a duration, which suspends the task but never blocks the loop itself.",
        "example": "await asyncio.sleep(0)      # let other tasks run now\nawait asyncio.sleep(0.05)   # pause this task 50ms",
        "usecase": "Fair sharing in loops and tiny debounce delays between steps.",
        "category": "asyncio",
    },
    {
        "id": 11,
        "title": "pacing uses sleep",
        "definition": "Inserting awaits of asyncio.sleep between workload chunks controls how fast a task consumes the loop — explicit pacing for rate limits, backpressure and polite polling. The pauses suspend the coroutine entirely, so throttling never wastes CPU while waiting.",
        "example": "async def sync_cursor(cursor, rate):\n    while rows := await cursor.next():\n        await process(rows)\n        await asyncio.sleep(1 / rate)",
        "usecase": "Respecting API rate limits and external service quotas from inside the loop.",
        "category": "asyncio",
    },
    {
        "id": 12,
        "title": "Event coordinates tasks",
        "definition": "asyncio.Event is a flag that tasks wait on: wait() suspends until set() is called, and is_set returns True instantly for latecomers. It wires producer-to-consumer signaling — data ready, shutdown requested, configuration changed — without polling or shared mutable state.",
        "example": "ready = asyncio.Event()\n\nasync def waiter():\n    await ready.wait()\n    print('go')\n\nasync def producer():\n    await asyncio.sleep(1)\n    ready.set()",
        "usecase": "Kicking off dependency-laden work in the right order across tasks.",
        "category": "asyncio",
    },
    {
        "id": 13,
        "title": "Lock serializes a section",
        "definition": "asyncio.Lock guarantees that only one task at a time holds it, so the guarded section never interleaves — acquire, mutate, release. Unlike threading locks it is awaited and loop-bound, serializing exactly the async critical section — caches, counters, connection checkout — without blocking the loop.",
        "example": "lock = asyncio.Lock()\n\nasync def bump(counter):\n    async with lock:\n        counter['n'] += 1",
        "usecase": "Protecting shared mutable state that awaits happen around.",
        "category": "asyncio",
    },
    {
        "id": 14,
        "title": "Semaphore caps the load",
        "definition": "asyncio.Semaphore(N) lets at most N tasks hold it simultaneously; every other acquirer suspends until a slot frees. Wrapping a heavy operation turns unlimited fan-out into a bounded pool, which is how concurrency limits are expressed without managing task lists by hand.",
        "example": "pool = asyncio.Semaphore(10)\n\nasync def limited(url):\n    async with pool:\n        return await fetch(url)",
        "usecase": "Capping open connections or parallel downloads at the service's tolerance.",
        "category": "asyncio",
    },
    {
        "id": 15,
        "title": "Queue distributes work",
        "definition": "asyncio.Queue is a FIFO channel between coroutines: producers put(), consumers await get() and mark finished with task_done(). It decouples the rate of production from consumption, which is exactly what a pipeline needs when producers and consumers run at different speeds.",
        "example": "q = asyncio.Queue()\n\nasync def producer():\n    for item in source():\n        await q.put(item)\n\nasync def consumer():\n    while item := await q.get():\n        await handle(item)\n        q.task_done()",
        "usecase": "Producer/consumer pipelines — crawl queues, render jobs, log drains.",
        "category": "asyncio",
    },
    {
        "id": 16,
        "title": "bounded queues add backpressure",
        "definition": "asyncio.Queue(maxsize=N) makes put() suspend once the queue is full, so producers slow down when consumers fall behind instead of buffering without limit. Bounded queues turn memory-hungry pipelines into self-limiting ones, and join() waits until every item has been processed.",
        "example": "q = asyncio.Queue(maxsize=100)\n\nawait q.put(item)      # waits while full\nawait q.join()         # waits until all task_done() calls",
        "usecase": "Pipelines that must bound memory and stall producers instead of crashing.",
        "category": "asyncio",
    },
    {
        "id": 17,
        "title": "TaskGroup supervises tasks",
        "definition": "The asyncio.TaskGroup context manager, new in Python 3.11, spawns tasks that are all awaited when the block exits; if any task raises, the group cancels the rest and re-raises a single ExceptionGroup. Supervision comes built in: no orphaned tasks, one collective outcome.",
        "example": "async with asyncio.TaskGroup() as tg:\n    tg.create_task(fetch('a'))\n    tg.create_task(fetch('b'))\n# all tasks finished here, or the failure propagated",
        "usecase": "Structured concurrency — fire several tasks and treat the group as one unit.",
        "category": "asyncio",
    },
    {
        "id": 18,
        "title": "shield protects a task",
        "definition": "asyncio.shield(coro) wraps an operation so that cancelling the await point does not cancel the underlying work; the operation keeps running to completion and only the waiting side raises CancelledError. The protection is one-way: direct cancellation of the inner task still works.",
        "example": "task = asyncio.create_task(long_upload())\ntry:\n    await asyncio.wait_for(asyncio.shield(task), timeout=10)\nexcept TimeoutError:\n    pass   # upload keeps going in the background",
        "usecase": "Best-effort flush paths — let the write finish even though the caller moved on.",
        "category": "asyncio",
    },
    {
        "id": 19,
        "title": "CancelledError is control flow",
        "definition": "task.cancel() injects a CancelledError at the task's current await point; catching it and swallowing breaks cancellation, so handlers should clean up and re-raise. Since the exception derives from BaseException, unchecked it unwinds the whole task — catching it deliberately is how controlled shutdown works.",
        "example": "try:\n    await work()\nexcept asyncio.CancelledError:\n    await cleanup()\n    raise",
        "usecase": "Cooperative shutdown where every task spins down its own resources.",
        "category": "asyncio",
    },
    {
        "id": 20,
        "title": "cancel runs cleanup first",
        "definition": "Cancelling a task surfaces as an exception inside it, so finally blocks and except-and-re-raise handlers run before the task finishes. That order — cancel, unwind, cleanup, done — lets each coroutine leave the world tidy whether it completes normally or is stopped.",
        "example": "async def worker():\n    conn = open_conn()\n    try:\n        await conn.loop()\n    finally:\n        await conn.close()   # runs even on cancel",
        "usecase": "Sessions, sockets and files that must close regardless of how the task ends.",
        "category": "asyncio",
    },
    {
        "id": 21,
        "title": "done tasks keep their result",
        "definition": "A finished Task stores its outcome: .result() returns the value or re-raises the exception, and .done() reports completion without blocking. Outcomes are retrievable after the task finished, which lets a coordinator wait for tasks and then inspect and collate what each one produced.",
        "example": "t = asyncio.create_task(fetch())\nawait asyncio.sleep(0.5)\nif t.done():\n    print(t.result())",
        "usecase": "Checking late-bound outcomes and surfacing failures at collection time.",
        "category": "asyncio",
    },
    {
        "id": 22,
        "title": "run_in_executor offloads work",
        "definition": "loop.run_in_executor(None, fn, *args) runs a synchronous function in a thread pool and returns an awaitable, so CPU-bound or blocking code runs off the loop. The default executor keeps a thread pool; passing a ProcessPoolExecutor moves heavy work across CPU cores.",
        "example": "result = await loop.run_in_executor(None, hashlib.sha256, big_blob)",
        "usecase": "Hashing, parsing and other synchronous calls that must run inside coroutines.",
        "category": "asyncio",
    },
    {
        "id": 23,
        "title": "to_thread wraps blocking calls",
        "definition": "asyncio.to_thread(fn, *args) is the one-liner version of run_in_executor: run this blocking function in another thread and await its result. It is the sanctioned escape hatch when no async alternative exists, and it keeps the loop responsive while the call blocks elsewhere.",
        "example": "data = await asyncio.to_thread(read_config_from_disk, path)",
        "usecase": "Individual blocking utility calls — file reads, orm queries — inside async handlers.",
        "category": "asyncio",
    },
    {
        "id": 24,
        "title": "blocking calls freeze the loop",
        "definition": "Calling a blocking function inside a coroutine — time.sleep instead of await asyncio.sleep, or a sync HTTP client — freezes every task in the process, because there is only one loop. The tell is obvious: one slow call pauses everything, so async code stays async end to end.",
        "example": "await asyncio.sleep(0.2)          # good: loop keeps running\ntime.sleep(0.2)                   # bad: entire loop stops",
        "usecase": "The rule of thumb for code review: if it blocks, it does not belong on the loop.",
        "category": "asyncio",
    },
    {
        "id": 25,
        "title": "async libraries wrap the blocking world",
        "definition": "The ecosystem replicates every blocking domain with async clients: aiofiles for files, aiosqlite and asyncpg for databases, httpx and aiohttp for HTTP. Reaching for the async version keeps one uniform model — await everywhere — instead of mixing loops and threads mid-flow.",
        "example": "import aiosqlite\n\nasync with aiosqlite.connect('app.db') as db:\n    async with db.execute('select id from users') as cur:\n        rows = await cur.fetchall()",
        "usecase": "Files, databases and HTTP providers inside fully async code paths.",
        "category": "asyncio",
    },
    {
        "id": 26,
        "title": "streams speak over sockets",
        "definition": "asyncio.open_connection returns a StreamReader/StreamWriter pair for protocol work — bare TCP with plain writes and reads, no threads and no raw socket API. Streams underpin higher-level clients, and they are the right level for custom protocols, heartbeats and anything needing fine control.",
        "example": "reader, writer = await asyncio.open_connection('localhost', 7000)\nwriter.write(b'ping\\n')\nawait writer.drain()\nline = await reader.readline()",
        "usecase": "Custom line-based protocols and lightweight TCP integrations.",
        "category": "asyncio",
    },
    {
        "id": 27,
        "title": "subprocesses run without shell",
        "definition": "asyncio.create_subprocess_exec launches a program with an argument list, no shell parsing, and returns a Process you await: exit status via wait(), output via communicate(). Long-running output streams out in one call, and the child never blocks the loop while running.",
        "example": "proc = await asyncio.create_subprocess_exec(\n    'ffmpeg', '-i', src, dst,\n    stdout=asyncio.subprocess.PIPE,\n)\nout, _ = await proc.communicate()",
        "usecase": "Running CLI tools and shell-free automation from async services.",
        "category": "asyncio",
    },
    {
        "id": 28,
        "title": "one loop per thread",
        "definition": "The event loop belongs to the thread that created it: get_event_loop changed meaning in Python 3.10, and get_running_loop raises outside an active loop. Code touching the loop from foreign threads needs run_coroutine_threadsafe, which is how GUIs and workers hand work across the boundary.",
        "example": "future = asyncio.run_coroutine_threadsafe(coro, loop)\nresult = future.result(timeout=5)",
        "usecase": "Bridging async tasks with GUI toolkits and non-async worker threads.",
        "category": "asyncio",
    },
    {
        "id": 29,
        "title": "debug mode traces the loop",
        "definition": "asyncio.run(main(), debug=True) or the PYTHONASYNCIODEBUG environment variable turns on diagnostics: slow coroutines are logged with their stacks, resource warnings fire, and unawaited coroutines are caught loudly. The debug loop also reports callback durations, exposing where real time is spent inside the loop.",
        "example": "import asyncio\n\nasyncio.run(main(), debug=True)",
        "usecase": "Hunting hidden blocking calls and stray coroutine objects in production-like runs.",
        "category": "asyncio",
    },
    {
        "id": 30,
        "title": "call_later fires a timer",
        "definition": "loop.call_later(seconds, callback, *args) schedules a plain function on the loop after a delay, returning a Handle that can be cancelled. Unlike awaited sleeps it runs fire-and-forget logic — timeouts, retries, expiry bookkeeping — attached to the loop's clock without a coroutine holding it open.",
        "example": "handle = loop.call_later(30, expire_session, session_id)\n# store the handle and cancel it on renewal",
        "usecase": "Session expiry, idle timeouts and scheduled housekeeping.",
        "category": "asyncio",
    },
    {
        "id": 31,
        "title": "call_soon queues the tick",
        "definition": "loop.call_soon(callback) schedules a callback for the next iteration of the loop in FIFO order, without blocking and without creating a task. It is the micro-level scheduling primitive — kick a callback, re-arm a watchdog — when the work is too small for a coroutine.",
        "example": "loop.call_soon(log_stats)",
        "usecase": "Tiny deferred actions and heartbeat callbacks from any context.",
        "category": "asyncio",
    },
    {
        "id": 32,
        "title": "Futures are raw promises",
        "definition": "An asyncio.Future is a one-shot holder that starts empty and later receives a value, an exception or a cancellation; awaiting it suspends until then. Tasks are futures with running coroutines attached, and the future is the mechanism run_coroutine_threadsafe and executors use to cross boundaries.",
        "example": "f = loop.create_future()\nset_result_elsewhere(f, 42)     # some other code path\nvalue = await f",
        "usecase": "Plumbing values between loops, threads and callbacks when a task is not the right fit.",
        "category": "asyncio",
    },
    {
        "id": 33,
        "title": "async with manages resources",
        "definition": "Entering an async context manager awaits __aenter__, and leaving awaits __aexit__; sessions, connections and files implement it, so cleanup is guaranteed on success and failure alike. The pattern reads exactly like the sync version, but each phase cooperates with the loop.",
        "example": "async with aiohttp.ClientSession() as session:\n    async with session.get(url) as resp:\n        body = await resp.text()",
        "usecase": "Connection and session lifetimes that must close reliably in async code.",
        "category": "asyncio",
    },
    {
        "id": 34,
        "title": "async for consumes streams",
        "definition": "Async iteration lets a producer yield values as they arrive: async for item in stream processes each one with awaits in between, while the next-item call suspends when nothing is ready. Streaming APIs — SSE feeds, paginated results, live logs — turn into plain loops.",
        "example": "async for event in sse_events(url):\n    if event.kind == 'order':\n        await handle_order(event)",
        "usecase": "Consuming infinite or incremental feeds without buffering them first.",
        "category": "asyncio",
    },
    {
        "id": 35,
        "title": "sessions need closing",
        "definition": "HTTP clients like aiohttp keep connection pools alive until they are closed; an unclosed session can hold sockets and keep the process running after the work is done. Making the session a context manager — async with aiohttp.ClientSession() — ties its lifetime to the block that uses it.",
        "example": "async with aiohttp.ClientSession() as session:\n    async with session.get(url) as resp:\n        return await resp.json()",
        "usecase": "Long-running services and scripts that must not leak sockets between requests.",
        "category": "asyncio",
    },
    {
        "id": 36,
        "title": "aiohttp fetches concurrently",
        "definition": "aiohttp provides the requests-style API without threads: session.get returns an awaitable that suspends, so gathering many requests runs them simultaneously over pooled connections. Concurrency goes from a threading burden to N awaited calls whose results come back in order.",
        "example": "async def fetch(session, url):\n    async with session.get(url) as resp:\n        return await resp.text()\n\nasync with aiohttp.ClientSession() as s:\n    pages = await asyncio.gather(*[fetch(s, u) for u in urls])",
        "usecase": "Scraping batches of pages and testing endpoints with real overlap.",
        "category": "asyncio",
    },
    {
        "id": 37,
        "title": "websockets keep conversations",
        "definition": "The websockets library hosts persistent two-way channels: a serve() listener, an async handler per connection, and await ws.recv() and ws.send() to converse. Long-lived push flows — chat, feeds, control panels — stay open without polling, and every frame suspends cooperatively.",
        "example": "import websockets\n\nasync def handler(ws):\n    async for msg in ws:\n        await ws.send(msg.upper())\n\nasync with websockets.serve(handler, 'localhost', 8765):\n    await asyncio.Future()   # serve forever",
        "usecase": "Real-time push features needing a durable socket per client.",
        "category": "asyncio",
    },
    {
        "id": 38,
        "title": "shutdown cancels everything",
        "definition": "Graceful shutdown is structured: signal handlers set an Event or cancel the fan-out, awaited tasks run their cleanup, and asyncio.run unwinds the rest. Waiting for tasks with return_exceptions=True collects every CancelledError, so the process exits only after all work wound down.",
        "example": "try:\n    await asyncio.wait_for(main_loop(), timeout=60)\nexcept TimeoutError:\n    for task in asyncio.all_tasks():\n        task.cancel()",
        "usecase": "Deployments and Ctrl-C paths that should drain work before exiting.",
        "category": "asyncio",
    },
    {
        "id": 39,
        "title": "timeouts cancel the inner task",
        "definition": "A wait_for timeout cancels the inner coroutine as part of raising TimeoutError, so slow-but-valuable work is stopped unless wrapped in a shield. Knowing this prevents surprise — a half-finished download is gone, not paused — and motivates shields for operations worth letting finish.",
        "example": "try:\n    await asyncio.wait_for(backup_job(), timeout=30)\nexcept TimeoutError:\n    pass   # the backup job got cancelled too",
        "usecase": "Deadlines that must also terminate the underlying work, not just the wait.",
        "category": "asyncio",
    },
    {
        "id": 40,
        "title": "coroutine objects await once",
        "definition": "A coroutine object executes exactly once; awaiting it twice raises RuntimeError, and restarting the work means calling the coroutine function again for a fresh object. Passing the function or a factory around, not a single coroutine, keeps every caller able to spawn its own instance.",
        "example": "coro = fetch()            # one execution, one await\nawait coro                # ok\nawait coro                # RuntimeError: cannot reuse",
        "usecase": "Task lists, retries and caches that must rebuild work instead of reusing it.",
        "category": "asyncio",
    },
    {
        "id": 41,
        "title": "asyncio.run cleans up after",
        "definition": "asyncio.run cancels pending tasks, closes the loop and closes the default executor before returning, which is why scripts end without lingering handlers keeping the process alive. Every run is self-contained, making it safe to bracket several independent async phases in one process.",
        "example": "asyncio.run(stage_one())\nasyncio.run(stage_two())   # fresh loop, clean state",
        "usecase": "CLI tools and tests that run multiple async phases in sequence.",
        "category": "asyncio",
    },
    {
        "id": 42,
        "title": "concurrency is not parallelism",
        "definition": "Async programs run one coroutine at a time on one thread; await points interleave them so IO overlaps, but CPU work never happens in parallel. That distinction decides the tool: gather for IO-bound fan-out, process pools for heavy compute — and explains why CPU-bound coroutines stall everyone.",
        "example": "# IO-bound: gather wins\nawait asyncio.gather(*[fetch(u) for u in urls])\n# CPU-bound: needs an executor instead\nawait loop.run_in_executor(pool, crunch, payload)",
        "usecase": "Choosing the right mechanism before performance work starts.",
        "category": "asyncio",
    },
    {
        "id": 43,
        "title": "shared data needs no locks here",
        "definition": "Because one thread executes all tasks and context switches only happen at await points, a dict updated between awaits is never raced by another task unless an await intervenes. Plain attributes stay safe without threading locks; only sections spanning awaits need an asyncio.Lock.",
        "example": "state = {}\n\nasync def tick():\n    state['n'] = state.get('n', 0) + 1     # safe: no await inside\n    await asyncio.sleep(0)",
        "usecase": "Thread-free shared counters and caches inside one-loop programs.",
        "category": "asyncio",
    },
    {
        "id": 44,
        "title": "windows picks its loop policy",
        "definition": "On Windows the default ProactorEventLoop handles sockets and subprocesses, but some libraries historically expect the SelectorEventLoop; asyncio.set_event_loop_policy swaps the policy globally. Framework documentation states which one it wants, so match the runtime to the stack instead of fighting it.",
        "example": "import asyncio\nimport sys\n\nif sys.platform == 'win32':\n    asyncio.set_event_loop_policy(\n        asyncio.WindowsSelectorEventLoopPolicy())",
        "usecase": "Portable codebases where CI machines and developers run Windows.",
        "category": "asyncio",
    },
    {
        "id": 45,
        "title": "start all, then await all",
        "definition": "The naive fan-out looks like a loop of awaits, which runs sequentially; scheduling every task first and awaiting afterwards runs them concurrently — create all tasks, then await them in one pass. The pattern is the two-line version of gather for dynamic task lists.",
        "example": "tasks = [asyncio.create_task(fetch(u)) for u in urls]\nresults = [await t for t in tasks]",
        "usecase": "Dynamic batches whose size is only known at runtime.",
        "category": "asyncio",
    },
    {
        "id": 46,
        "title": "retries live in the coroutine",
        "definition": "Retry logic becomes ordinary code inside async functions: loop a few attempts, await the operation, sleep bounded backoff between them, and surface the last error. Sleeping is safe inside the coroutine, so backoff never blocks other tasks and the policy stays readable next to the operation it guards.",
        "example": "async def fetch_with_retry(url, attempts=3):\n    for i in range(attempts):\n        try:\n            return await fetch(url)\n        except ConnectionError:\n            await asyncio.sleep(2 ** i)\n    raise ConnectionError('still down')",
        "usecase": "API clients and jobs that must survive transient failures.",
        "category": "asyncio",
    },
    {
        "id": 47,
        "title": "all_tasks shows the state",
        "definition": "asyncio.all_tasks(loop=None) returns every task still scheduled or running on the loop — the raw inventory for shutdown and diagnostics. Inspecting it before exiting tells you what is actually in flight, and cancelling the whole set is the blunt instrument for draining a program.",
        "example": "pending = asyncio.all_tasks()\nprint(len(pending))\nfor task in pending:\n    task.cancel()\nawait asyncio.gather(*pending, return_exceptions=True)",
        "usecase": "Shutdown hygiene and answering 'what is still running?' questions.",
        "category": "asyncio",
    },
    {
        "id": 48,
        "title": "async generators clean up",
        "definition": "Async generators owning resources release them when aclose() runs their finally blocks, so sessions and cursors held inside are closed when iteration stops early. Under the debug mode an unclosed async generator warns loudly, keeping streams from silently holding sockets open.",
        "example": "async def pages():\n    async with aiohttp.ClientSession() as s:\n        for i in range(3):\n            async with s.get(f'{base}/{i}') as resp:\n                yield await resp.text()\n\nasync for html in pages():\n    break          # the generator's finally runs: session closed",
        "usecase": "Resource-owning streams that must release on early exit.",
        "category": "asyncio",
    },
    {
        "id": 49,
        "title": "batch deadlines stack outside",
        "definition": "Wrap a gather in wait_for to bound an entire batch: every inner call shares one deadline, and the batch timeout cancels the pending calls wholesale. Inner per-call timeouts plus one outer deadline give two layers — slow items fail small, a stuck batch fails big.",
        "example": "try:\n    rows = await asyncio.wait_for(\n        asyncio.gather(*[fetch(u) for u in urls]), timeout=30)\nexcept TimeoutError:\n    log.error('batch deadline passed')",
        "usecase": "SLA-bounded fan-out where the whole batch has a deadline in addition to each call.",
        "category": "asyncio",
    },
    {
        "id": 50,
        "title": "one async main shapes the app",
        "definition": "Cohesive programs run one async main: asyncio.run(async_main()) with startup, lifetimes and shutdown inside it, rather than top-level awaits or scattered loops. Dependencies, queues and tasks are born inside the main scope, so cancellation and cleanup follow the same structure end to end.",
        "example": "async def main():\n    async with aiohttp.ClientSession() as s:\n        rows = await fetch_rows(s)\n    await store(rows)\n\nasyncio.run(main())",
        "usecase": "Application skeletons whose lifecycle is one coroutine from first await to last.",
        "category": "asyncio",
    },
]