TIPS = [
    {
        "id": 1,
        "title": "tasks decorate functions",
        "definition": "Celery converts an ordinary function into a distributed task with @app.task, giving it .delay and .apply_async methods and the machinery to run on any worker. The function stays a normal callable — tested in-process, imported anywhere — while the decorator adds the queue interface around it.",
        "example": "from celery import Celery\n\napp = Celery('tasks', broker='redis://localhost:6379/0')\n\n@app.task\ndef add(x, y):\n    return x + y",
        "usecase": "Turning existing functions into background jobs without changing their bodies.",
        "category": "celery",
    },
    {
        "id": 2,
        "title": "delay submits the job",
        "definition": "Calling add.delay(1, 2) serializes the arguments, sends a message to the broker and returns an AsyncResult with a fresh task id — the function body runs later on some worker. The sender never waits for execution, which is the whole point of handing work off to the queue.",
        "example": "result = add.delay(4, 4)       # enqueued immediately\nprint(result.id)               # traceable task id",
        "usecase": "Fire-and-forget background work from web requests and scripts.",
        "category": "celery",
    },
    {
        "id": 3,
        "title": "apply_async brings options",
        "definition": "apply_async is delay's full form: same call, but with options like countdown, eta, expires, queue and task_id attached to the message. Anything delay hides — scheduling, routing, timeouts — is set here, and delay is simply apply_async with defaults.",
        "example": "result = add.apply_async((4, 4), countdown=10, queue='math')",
        "usecase": "Enqueueing with per-message scheduling and routing choices.",
        "category": "celery",
    },
    {
        "id": 4,
        "title": "workers run the queue",
        "definition": "The worker is the execution side: celery -A proj worker picks messages off the broker and runs their tasks, taking every task function along. One worker handles many tasks of many types, distributes across multiple processes, and its logs show the queue-to-execution path.",
        "example": "# terminal\ncelery -A proj worker --loglevel=info --concurrency=4",
        "usecase": "Starting the processes that actually execute the queued work.",
        "category": "celery",
    },
    {
        "id": 5,
        "title": "brokers carry messages",
        "definition": "The broker is the transport between producers and workers — Redis or RabbitMQ in practice — a durable queue of serialized task messages. Producers write, workers read, and the broker's job is to not lose messages even when workers restart mid-drain.",
        "example": "app = Celery(\n    'animals',\n    broker='redis://localhost:6379/0',\n    backend='redis://localhost:6379/1',\n)",
        "usecase": "Choosing the transport your infrastructure already runs.",
        "category": "celery",
    },
    {
        "id": 6,
        "title": "backends store results",
        "definition": "The result backend is where finished tasks put their return values and failure traces, keyed by task id. Producers and monitors later fetch them with AsyncResult; without a backend, .get() raises NotImplementedError and the results are simply discarded.",
        "example": "app = Celery('tasks', backend='redis://localhost:6379/1')\n# after add.delay(1, 2), the backend holds the value 3",
        "usecase": "Getting return values across processes — the memory of what each task produced.",
        "category": "celery",
    },
    {
        "id": 7,
        "title": "AsyncResult checks the outcome",
        "definition": "An AsyncResult wraps a task id and turns it into questions: .ready() for done, .successful() for a clean finish, .get() for the return value, and .failed() with .traceback for failures. It is the API for follow-ups — poll a background job, then react to its outcome.",
        "example": "result = add.delay(4, 4)\nif result.ready():\n    print(result.get(timeout=3))\nelse:\n    print('still running, id', result.id)",
        "usecase": "Waiting, polling and failure inspection from producers or monitors.",
        "category": "celery",
    },
    {
        "id": 8,
        "title": "task ids trace every job",
        "definition": "Every task message carries a unique id that flows from producer to worker to backend, connecting the enqueue point with execution logs and stored results. Logging the id at submission and in worker output is the breadcrumb trail for debugging distributed work.",
        "example": "res = files.process_batch.delay(paths)\nlogger.info('batch %s submitted', res.id)",
        "usecase": "Correlating submitted jobs with their execution and results later.",
        "category": "celery",
    },
    {
        "id": 9,
        "title": "retries come built in",
        "definition": "Tasks retry natively: max_retries caps attempts, autoretry_for retries on listed exceptions automatically, and retry() inside the task re-enqueues the message by hand. Retry state is persisted in the broker, so attempts survive worker restarts without inventing your own retry loop.",
        "example": "@app.task(autoretry_for=(ConnectionError,),\n          retry_backoff=True, max_retries=5)\ndef ping_service(host):\n    return connect(host)",
        "usecase": "APIs and flaky services where transient failures are the norm.",
        "category": "celery",
    },
    {
        "id": 10,
        "title": "countdown and eta schedule later",
        "definition": "countdown=N delays the message by N seconds, while eta=datetime pins it to an absolute time — the difference between relative and absolute scheduling. Both keep the message in the broker until due, so no clock is consumed by the producer and the scheduling survives restarts.",
        "example": "later = reminder.send.delay('invoice', countdown=3600)\nnoon = reminder.send.apply_async(\n    ('invoice',), eta=datetime(2026, 8, 21, 12, 0))",
        "usecase": "Reminders, grace periods and absolute-time releases.",
        "category": "celery",
    },
    {
        "id": 11,
        "title": "expires drops stale work",
        "definition": "The expires option stamps a message with a deadline, and undelivered messages past it are discarded instead of piling up. Backlog safety — a retried job worth nothing once the report deadline passed — cuts queue pollution without extra cleanup workers.",
        "example": "res = report.build.apply_async(args=(date,), expires=600)",
        "usecase": "Time-sensitive jobs where running late is worse than not running.",
        "category": "celery",
    },
    {
        "id": 12,
        "title": "time limits stop runaways",
        "definition": "task_time_limit hard-kills a task that overruns, and task_soft_time_limit lets it catch SoftTimeLimitExceeded to stop gracefully first. Both are per-task or global settings that keep one stuck job from holding a worker slot forever.",
        "example": "@app.task(time_limit=300, soft_time_limit=240)\ndef analyze(blob):\n    return crunch(blob)",
        "usecase": "Guarding workers against infinite loops and silent hangs.",
        "category": "celery",
    },
    {
        "id": 13,
        "title": "acks tell when work is done",
        "definition": "By default the broker is told done as soon as the worker receives the message; task_acks_late moves the ack to after successful execution. With late acks, a crashing worker returns the message to the queue for redelivery, trading at-least-once for guaranteed processing.",
        "example": "task_acks_late = True   # in app config or command line",
        "usecase": "Jobs whose loss is unacceptable, where a retry beats a silent gap.",
        "category": "celery",
    },
    {
        "id": 14,
        "title": "failure acks decide redelivery",
        "definition": "Default late-ack behavior still acknowledges a task that raises, treating the exception as final, so failed work is not endlessly redelivered. acks_on_failure_or_timeout=False flips that: a task that errored is put back for another attempt — pair it with explicit retry policies rather than blind redelivery.",
        "example": "task_acks_late = True\ntask_acks_on_failure_or_timeout = False   # only for truly retriable failures",
        "usecase": "Guaranteed-processing pipelines where even failures may be transient.",
        "category": "celery",
    },
    {
        "id": 15,
        "title": "results expire on their own",
        "definition": "Stored results accumulate in the backend forever unless result_expires, defaulting to one day, prunes them. Busy systems emitting thousands of results need an explicit window — hours or minutes — so the backend does not fill with data nobody reads.",
        "example": "app.conf.result_expires = 3600 * 4   # keep results for 4 hours",
        "usecase": "High-throughput queues where the backend would otherwise balloon.",
        "category": "celery",
    },
    {
        "id": 16,
        "title": "ignore_result saves the wire",
        "definition": "Tasks decorated with ignore_result=True skip writing to the backend entirely, saving serialization and storage on every run. The rule of thumb: only tasks whose outcome others actually fetch — or that need tracebacks — pay the backend cost.",
        "example": "@app.task(ignore_result=True)\ndef log_event(payload):\n    db.insert(payload)",
        "usecase": "Fire-and-forget work like logging and notifications that no one reads back.",
        "category": "celery",
    },
    {
        "id": 17,
        "title": "chain sequences tasks",
        "definition": "A chain pipes tasks so each one's return value becomes the next one's first argument: chain(a, b, c) runs a, then b with a's result, then c with b's. It expresses pipelines declaratively from the producer side instead of tasks calling tasks.",
        "example": "from celery import chain\n\nres = chain(download.s(url), parse.s(), store.s())().get()",
        "usecase": "Multi-stage processing — fetch, transform, persist — as one declarative flow.",
        "category": "celery",
    },
    {
        "id": 18,
        "title": "group fans out in parallel",
        "definition": "A group sends every task at once and their results come back as a list matching the input order: group(task.s(x) for x in xs)().get(). The fan-out happens inside the broker, which is how one batch request becomes N parallel executions.",
        "example": "from celery import group\n\nres = group(thumbnail.s(img) for img in images)()\nrows = res.get(timeout=60)",
        "usecase": "Resizing a batch, fetching many pages, validating a dataset.",
        "category": "celery",
    },
    {
        "id": 19,
        "title": "chord follows a group",
        "definition": "A chord attaches a callback that runs only after the whole group finished, receiving the group's results as its argument. It is the map-reduce primitive: fan out into workers, then reduce or post-process the collected results in one final task.",
        "example": "from celery import group, chord\n\nres = chord(group(crawl.s(u) for u in urls), summarize.s())().get()",
        "usecase": "Aggregation jobs — scrape everything, then count what came back.",
        "category": "celery",
    },
    {
        "id": 20,
        "title": "chunks split huge ranges",
        "definition": "task.chunks(items, n) breaks a large input sequence into groups and schedules one task per chunk, keeping individual messages small. Instead of a million tasks, a million items become a few hundred messages, each one processing a slice.",
        "example": "jobs = update_cache.chunks(rows, 1000)\nfor single in jobs:\n    single.apply_async()",
        "usecase": "Bulk operations over records too large for one message.",
        "category": "celery",
    },
    {
        "id": 21,
        "title": "map and starmap call per item",
        "definition": "task.map and task.starmap enqueue one task per input element in a group-like pattern, distributing each item across the pool. They turn apply-to-every-element into distributed execution with results returned in input order.",
        "example": "res = md5s.starmap([(b,) for b in blocks])().get(timeout=30)",
        "usecase": "Element-wise jobs over balanced real-world batches.",
        "category": "celery",
    },
    {
        "id": 22,
        "title": "in-process calls skip the queue",
        "definition": "Calling the underlying function directly — add(4, 4) — runs in the current process with no broker, message or worker, while task.apply() executes locally but returns a result object. Tests and quick scripts lean on this; production paths choose delay to stay off the queue.",
        "example": "total = add(4, 4)              # plain call, nothing queued\nres = add.apply((4, 4))       # local execution, result object",
        "usecase": "Unit tests and prototypes that must not touch the broker.",
        "category": "celery",
    },
    {
        "id": 23,
        "title": "workers need the new code",
        "definition": "Workers import task code at startup, so a deploy that changes a task's implementation requires a worker restart to take effect. The queue holds messages while workers cycle, so restarts are safe — but forgetting the restart runs old code in silence.",
        "example": "# deploy the new code, then restart the workers\n# terminal\ncelery -A proj worker -Q jobs,priority --loglevel=info",
        "usecase": "Ship-then-restart discipline in deployment pipelines.",
        "category": "celery",
    },
    {
        "id": 24,
        "title": "signatures shape the workflow",
        "definition": "task.s(args) builds a signature — a serializable recipe for one call — which is the building block of chain, group and chord. Signatures can carry queues and timeouts, and they travel anywhere as messages, which is how whole workflows get composed and sent.",
        "example": "sig = add.s(4, 4)          # recipe, not execution\nsig.apply_async(queue='math', countdown=5)",
        "usecase": "Composing and reusing executable recipes across endpoints.",
        "category": "celery",
    },
    {
        "id": 25,
        "title": "queues route the messages",
        "definition": "task_routes maps task names to named queues, and workers start with -Q to consume only their queues. Routing separates traffic — fast API jobs, slow batch work, priority lanes — so one broker carries many pipelines that never compete for the same slots.",
        "example": "app.conf.task_routes = {\n    'jobs.pdf.*': {'queue': 'pdf'},\n    'jobs.billing.*': {'queue': 'billing'},\n}",
        "usecase": "Dedicated lanes for latency-sensitive and batch workloads.",
        "category": "celery",
    },
    {
        "id": 26,
        "title": "prefetch controls the pileup",
        "definition": "worker_prefetch_multiplier, default 4, decides how many tasks a worker fetches per execution slot ahead of time — a buffer against slow brokers. Large multipliers can starve other workers or delay rate-limit enforcement, so busy deployments tune it down.",
        "example": "app.conf.worker_prefetch_multiplier = 1   # stricter fairness",
        "usecase": "Balanced consumption and prompt rate-limit enforcement across workers.",
        "category": "celery",
    },
    {
        "id": 27,
        "title": "visibility keeps jobs moving",
        "definition": "Redis uses a visibility timeout for unacked messages: a task still being processed past it becomes visible again and may be redelivered, even mid-run. Long tasks need broker_transport_options visibility_timeout raised, or duplicate executions are inevitable.",
        "example": "app.conf.broker_transport_options = {'visibility_timeout': 3600}",
        "usecase": "Multi-hour jobs on Redis brokers that otherwise redeliver mid-flight.",
        "category": "celery",
    },
    {
        "id": 28,
        "title": "beats runs schedules",
        "definition": "Celery Beat is the scheduler: it reads app.conf.beat_schedule and enqueues tasks at their configured moments, one entry per recurring job. Beat only sends messages — workers still run separately — making periodic execution independent of the executing side.",
        "example": "app.conf.beat_schedule = {\n    'cleanup-every-5m': {\n        'task': 'jobs.cleanup',\n        'schedule': 300.0,\n    },\n}",
        "usecase": "Recurring maintenance like purging caches and pruning tables.",
        "category": "celery",
    },
    {
        "id": 29,
        "title": "crontab shapes the schedule",
        "definition": "crontab() expressions in beat_schedule give cron-style timing — minutes, hours, days of week — for schedules that are not plain intervals. Morning reports at 06:30 on weekdays and nightly reboots read exactly like the cron files they replace.",
        "example": "from celery.schedules import crontab\n\nschedule = crontab(minute=30, hour=6, day_of_week='mon-fri')",
        "usecase": "Calendar-shaped jobs that a fixed interval cannot express.",
        "category": "celery",
    },
    {
        "id": 30,
        "title": "beat runs as its own process",
        "definition": "Beat and workers are separate processes: celery -A proj beat runs the scheduler and celery -A proj worker runs execution, and they can even live on different machines sharing the broker. The split matters because one beat is normally enough while workers scale horizontally.",
        "example": "# terminal\ncelery -A proj beat --loglevel=info\ncelery -A proj worker --loglevel=info",
        "usecase": "Production topologies where scheduler and executors scale independently.",
        "category": "celery",
    },
    {
        "id": 31,
        "title": "flower watches the fleet",
        "definition": "Flower serves a live dashboard for the cluster: task states, worker heartbeats, arguments, retries and results per task id — plus the ability to revoke and requeue. It turns the broker's internal messages into an operationally visible picture.",
        "example": "# terminal\npip install flower\ncelery -A proj flower --port=5555",
        "usecase": "Operations dashboards and human triage of stuck or retried work.",
        "category": "celery",
    },
    {
        "id": 32,
        "title": "backoff paces the retries",
        "definition": "retry_backoff=True multiplies waits between retry attempts — one second, two, four — and retry_jitter jitters the sleeps so a restarted fleet does not retry in lockstep. Together they stop thundering herds of simultaneous re-enqueues after an outage.",
        "example": "@app.task(autoretry_for=(TimeoutError,), retry_backoff=True,\n          retry_backoff_max=300, retry_jitter=True, max_retries=10)\ndef refresh(host):\n    return fetch(host)",
        "usecase": "Outage recovery where synchronized retries would recreate the outage.",
        "category": "celery",
    },
    {
        "id": 33,
        "title": "idempotency is your job",
        "definition": "Deliveries can repeat — late acks, visibility timeouts, manual requeues — so tasks should tolerate running twice. Dedup keys in the database, unique constraints and checking already-done markers turn at-least-once delivery into exactly-once behavior at the application level.",
        "example": "def process_order(order_id):\n    if db.exists(order_id):\n        return   # already handled, safe on redelivery\n    db.mark_processing(order_id)\n    charge(order_id)",
        "usecase": "Payment flows and mailouts where duplicates cost real money.",
        "category": "celery",
    },
    {
        "id": 34,
        "title": "bind gives the task itself",
        "definition": "Decorating with bind=True passes the task instance as the first argument, opening access to self.request, self.retry() and per-task configuration. Tasks that re-enqueue themselves, adjust deadlines or read delivery details need the bound self.",
        "example": "@app.task(bind=True)\ndef job(self, payload):\n    if not ready(payload):\n        raise self.retry(countdown=30)",
        "usecase": "Self-aware tasks that schedule their own next attempt.",
        "category": "celery",
    },
    {
        "id": 35,
        "title": "request holds the context",
        "definition": "Inside a bound task, self.request carries the runtime context: task id, args, delivery info, retries and the consumer's hostname. Logging these fields turns task output into traceable records matching the producer's result id.",
        "example": "@app.task(bind=True)\ndef tracked(self, x):\n    logger.info('rundown %s args %s', self.request.id, self.request.args)",
        "usecase": "Correlating logs across producers, workers and monitors.",
        "category": "celery",
    },
    {
        "id": 36,
        "title": "globals leak across tasks",
        "definition": "Workers reuse pool processes across many tasks, so module-level state is shared and persists between executions — a classic source of bugs and data leaks. Per-task data belongs in task arguments or request state, and caches designed for sharing need explicit, bounded lifetimes.",
        "example": "# bad: mutable global survives across tasks\n_scores = {}\n\n@app.task\ndef score(x):\n    _scores[x] = compute(x)   # may bleed into the next task",
        "usecase": "Writing tasks that stay correct under process reuse.",
        "category": "celery",
    },
    {
        "id": 37,
        "title": "tests bypass the broker",
        "definition": "Testing tasks without a broker means calling the inner function directly, or using the celery_worker fixture from the celery package to run against a live in-process worker. Units verify the logic; the fixture verifies the queue contract — message in, result out, retries behave.",
        "example": "# pytest\ndef test_add_logic():\n    assert add.run(2, 3) == 5        # no broker needed\n\ndef test_add_via_worker(celery_worker):\n    assert add.delay(2, 3).get(timeout=5) == 5",
        "usecase": "Fast unit tests plus honest integration tests for the queue path.",
        "category": "celery",
    },
    {
        "id": 38,
        "title": "eager mode runs inline",
        "definition": "task_always_eager makes delay execute synchronously in the process that calls it, bypassing broker and worker entirely — handy in tests or when the queue is temporarily unavailable. The call still returns a result object, so producer code does not change.",
        "example": "app.conf.task_always_eager = True     # dev/test only\nres = add.delay(1, 2)                  # runs inline, no broker",
        "usecase": "Test suites and demos that must not require a running broker.",
        "category": "celery",
    },
    {
        "id": 39,
        "title": "serializers choose the format",
        "definition": "Messages serialize their payloads before hitting the broker: json by default, plus pickle, yaml and msgpack, and compression like gzip for bulky fields. JSON keeps messages portable and safe; pickle enables arbitrary objects but must never process untrusted input.",
        "example": "app.conf.task_serializer = 'json'\napp.conf.task_compression = 'gzip'    # for bulky payloads",
        "usecase": "Trades between portability, flexibility and message size.",
        "category": "celery",
    },
    {
        "id": 40,
        "title": "celery plays with django",
        "definition": "The celery app lives next to Django via the standard wiring: the app is created in proj/celery.py, autodiscover_tasks loads each app's tasks module, and settings are read from django.conf with a CELERY prefix — then celery -A proj runs with full project context.",
        "example": "# proj/celery.py\napp = Celery('proj')\napp.config_from_object('django.conf:settings', namespace='CELERY')\napp.autodiscover_tasks()\n\n# any app/tasks.py\nfrom proj.celery import app\n\n@app.task\ndef refresh_cache():\n    cache.clear()",
        "usecase": "Django projects that need the ORM and settings inside their tasks.",
        "category": "celery",
    },
    {
        "id": 41,
        "title": "shared_task serves libraries",
        "definition": "shared_task comes from celery, not the app, so reusable libraries define tasks without importing your specific Celery instance. The task binds to whatever app loads it at runtime, which keeps library code app-agnostic and installable anywhere.",
        "example": "from celery import shared_task\n\n@shared_task\ndef stamp_auth(event):\n    audit(event)",
        "usecase": "Packages and internal libraries that ship their own tasks.",
        "category": "celery",
    },
    {
        "id": 42,
        "title": "custom task classes extend",
        "definition": "The base= argument points at a Task subclass, letting projects bake common behavior — logging, metrics, shared retry policies, result cleanup — into every task it decorates. One class replaces dozens of duplicated decorator options.",
        "example": "from celery import Task\n\nclass LoggedTask(Task):\n    def __call__(self, *args, **kwargs):\n        log_start(self.request.id)\n        try:\n            return super().__call__(*args, **kwargs)\n        finally:\n            log_finish(self.request.id)\n\n@app.task(base=LoggedTask)\ndef dependable(x):\n    return x * 2",
        "usecase": "Cross-cutting concerns applied once to a whole task family.",
        "category": "celery",
    },
    {
        "id": 43,
        "title": "soft limits signal politely",
        "definition": "With a soft time limit set, a task exceeding it gets a SoftTimeLimitExceeded exception it can catch — finishing up, saving state and returning a meaningful result instead of being hard-killed. Pairing soft and hard limits gives one graceful and one military option.",
        "example": "from celery.exceptions import SoftTimeLimitExceeded\n\n@app.task(time_limit=60, soft_time_limit=50)\ndef batch(x):\n    try:\n        return crunch(x)\n    except SoftTimeLimitExceeded:\n        return last_snapshot(x)",
        "usecase": "Long jobs that should degrade gracefully when their budget runs out.",
        "category": "celery",
    },
    {
        "id": 44,
        "title": "signals hook the lifecycle",
        "definition": "Celery emits signals at each stage — task_prerun, task_postrun, task_success, task_failure, worker_ready — and handlers subscribe with a connect API similar to Django. Monitoring, metrics and alerting hook into the pipeline without touching task bodies.",
        "example": "from celery.signals import task_failure\n\n@task_failure.connect\ndef on_failure(sender, task_id, exception, **kwargs):\n    alert.send(task_id=task_id, error=str(exception))",
        "usecase": "Central failure dashboards and SLO tracking across the cluster.",
        "category": "celery",
    },
    {
        "id": 45,
        "title": "rate limits calm the stampede",
        "definition": "The rate_limit option bounds executions in time units — '10/s' or '30/m' — enforced by the worker before running each unit of work. External APIs and paid services behind tasks get their consumption capped in the queue layer instead of inside every task body.",
        "example": "@app.task(rate_limit='10/m')\ndef call_partner_api(payload):\n    return partner.submit(payload)",
        "usecase": "Throttling calls to rate-limited upstream services.",
        "category": "celery",
    },
    {
        "id": 46,
        "title": "worker children recycle",
        "definition": "worker_max_tasks_per_child tells each pool process to restart after N executed tasks, flushing leaked memory and stale state automatically. Long-running workers with gradual leaks or memory creep set a sensible cap and avoid silent degradation.",
        "example": "# terminal\ncelery -A proj worker --max-tasks-per-child=200",
        "usecase": "Stabilizing workers under slow memory leaks in third-party code.",
        "category": "celery",
    },
    {
        "id": 47,
        "title": "names avoid collisions",
        "definition": "Task names default to module.function and are locked per module in the registry; two different functions with the same name in one app collide loudly and silently reroute. Explicit name= on the decorator, or a module prefix convention, keeps multi-team fleets unambiguous.",
        "example": "@app.task(name='ops.reports.build_daily')\ndef build_daily():\n    return report_for('daily')",
        "usecase": "Large codebases where short task names could collide.",
        "category": "celery",
    },
    {
        "id": 48,
        "title": "deployments supervise workers",
        "definition": "Workers are long-running daemons and need a supervisor: systemd units, supervisor, Docker restart policies or Kubernetes deployments keep them up, restart on crash and drain before shutdown. The broker rides the same restart wave, so supervision is the deployment contract.",
        "example": "# systemd unit sketch\n[Unit]\nDescription=Celery worker\n[Service]\nExecStart=celery -A proj worker -l info\nRestart=always\nKillSignal=SIGTERM",
        "usecase": "Production resilience when a worker crash must not end the queue.",
        "category": "celery",
    },
    {
        "id": 49,
        "title": "brokers persist through restarts",
        "definition": "Redis and RabbitMQ persist queued messages by default, so a broker restart does not lose pending work; workers redeliver unacked messages when they return. Connection settings like broker_connection_retry_on_startup make producers survive broker blips as well.",
        "example": "app.conf.broker_connection_retry_on_startup = True",
        "usecase": "Infrastructure restarts that must not swallow queued jobs.",
        "category": "celery",
    },
    {
        "id": 50,
        "title": "small tasks transfer best",
        "definition": "Tasks travel as serialized messages, so arguments should be plain data — ids, numbers, strings — not connections, file handles or huge objects. Workers fetch what they need inside the task, keeping messages small, serializers safe and retries cheap.",
        "example": "# good: pass an id, open the file inside the task\nprocess_upload.delay(upload_id)\n\n# bad: pass a file object across the broker\n# process_upload.delay(open('x', 'rb'))",
        "usecase": "Message hygiene that scales from dev boxes to production fleets.",
        "category": "celery",
    },
]