TIPS = [
    {
        "id": 1,
        "title": "assert is all you need",
        "definition": "pytest replaces the dozens of assertEqual, assertTrue and assertRaises methods of unittest with one tool: the plain Python assert. Any expression that evaluates false fails the test, and pytest rewrites the statement to show both sides of the comparison in the failure message, so no special assertion methods are needed.",
        "example": "def test_discount():\n    price = 120.0\n    discounted = price * 0.8\n    assert discounted == 96.0\n    assert discounted < price",
        "usecase": "Everything from unit checks to integration invariants, expressed in the same language you already write.",
        "category": "pytest",
    },
    {
        "id": 2,
        "title": "test discovery finds the tests",
        "definition": "pytest collects tests by convention: files named test_*.py or *_test.py, functions named test_*, and classes named Test*. Running pytest from the project root walks the tree automatically, finds every matching test and runs it, so no registration or import blocks are required for new tests.",
        "example": "# tests/test_cart.py — discovered automatically\n\ndef test_add_item():\n    cart = Cart()\n    cart.add('apple')\n    assert cart.count == 1",
        "usecase": "Zero-configuration test suites that grow by adding files and functions.",
        "category": "pytest",
    },
    {
        "id": 3,
        "title": "failures explain themselves",
        "definition": "When an assert fails, pytest's assertion rewriting displays the actual values of both sides: assert a == b prints a and b, and compound expressions show every sub-value. That introspection turns a bare False into a diagnosable diff, which is why the plain assert produces better messages than bespoke assertion helpers.",
        "example": "def test_billing():\n    line_total = 33.33\n    calc_total = 33.34\n    assert line_total == calc_total\n    # failure shows: assert 33.33 == 33.34",
        "usecase": "Locating the wrong value in seconds, especially on CI where no debugger is available.",
        "category": "pytest",
    },
    {
        "id": 4,
        "title": "fixtures provide the setup",
        "definition": "A fixture is a function decorated with @pytest.fixture whose return value is injected into any test that names it as a parameter. The test declares what it needs, pytest orchestrates ordering and sharing, and the setup lives exactly where it is reused instead of being copied into every test that needs it.",
        "example": "import pytest\n\n@pytest.fixture\ndef client():\n    return TestClient(app)\n\ndef test_home(client):\n    r = client.get('/')\n    assert r.status_code == 200",
        "usecase": "Customers, clients, databases and mocks needed by many tests, prepared in one place.",
        "category": "pytest",
    },
    {
        "id": 5,
        "title": "fixture scope controls lifetime",
        "definition": "The scope argument decides when a fixture is created and torn down: function for every test, class once per class, module once per file, and session once per whole run. Heavy setup like database containers or API servers belongs at session or module scope, while cheap per-test state stays at function scope.",
        "example": "@pytest.fixture(scope='session')\ndef db_pool():\n    pool = create_pool(DB_URL)\n    yield pool\n    pool.close()",
        "usecase": "Spinning up slow resources once per run and fast ephemeral state per test.",
        "category": "pytest",
    },
    {
        "id": 6,
        "title": "yield turns setup into cleanup",
        "definition": "A yield fixture splits into two phases: everything before yield runs as setup and its value gets injected, while everything after yield runs when the test finishes. That makes symmetric setup and teardown trivial — build a resource, yield it, then release it — and the post-yield code still runs even when a test fails.",
        "example": "@pytest.fixture\ndef conn():\n    c = connect()       # setup\n    yield c             # injected into the test\n    c.close()           # teardown, always runs",
        "usecase": "Files, sockets, connections and temporary state that must be cleaned up whatever happens.",
        "category": "pytest",
    },
    {
        "id": 7,
        "title": "fixtures use fixtures",
        "definition": "Fixtures request other fixtures the exact same way tests do — as parameters. A user fixture can depend on a db fixture, which in turn depends on a config fixture, and pytest resolves the whole graph, builds in dependency order and caches per scope, so the plumbing never appears in the test bodies themselves.",
        "example": "@pytest.fixture\ndef user(db):\n    return create_user(db, email='ada@example.com')\n\ndef test_profile(user):\n    assert user.profile()['email'] == 'ada@example.com'",
        "usecase": "Composing setup layers — config, database, session, and finally the business object under test.",
        "category": "pytest",
    },
    {
        "id": 8,
        "title": "conftest shares the setup",
        "definition": "conftest.py files sit at directory roots and make their fixtures and hooks available to every test below them without imports. Project-wide fixtures go in a top-level conftest, while per-subdirectory conftest files scope shared fixtures to that part of the suite — the natural home for app-wide test infrastructure.",
        "example": "# tests/conftest.py — usable by all tests under tests/\nimport os\nimport pytest\n\n@pytest.fixture\ndef staging_url():\n    os.environ['APP_ENV'] = 'staging'\n    return 'http://testserver'",
        "usecase": "Sharing clients, factories and environment setup across whole test directories.",
        "category": "pytest",
    },
    {
        "id": 9,
        "title": "parametrize runs the cases",
        "definition": "The @pytest.mark.parametrize decorator runs one test function many times, once per listed case, and a failure in any case is reported independently of the rest. Each row is a separate test outcome, so one bad input never hides the other fifteen — the standard way to cover boundary values and table-driven cases.",
        "example": "import pytest\n\n@pytest.mark.parametrize('items, expected', [\n    ([], 0),\n    ([1], 1),\n    ([1, 2, 3], 6),\n])\ndef test_sum(items, expected):\n    assert mysum(items) == expected",
        "usecase": "Edge cases, chunk sizes and API states expressed as one table of inputs.",
        "category": "pytest",
    },
    {
        "id": 10,
        "title": "ids keep failures readable",
        "definition": "Parametrized cases can be renamed with ids= to friendly labels, producing test names like test_shipping[bulk] instead of test_shipping[3]. Report diffs and CI logs stay readable, and case labels can be generated per row with functions, so wide tables remain navigable even with dozens of inputs.",
        "example": "import pytest\n\n@pytest.mark.parametrize('qty, expected', [\n    (1, '$1.99'),\n    (4, '$4.99'),\n    (5, '$5.99'),\n], ids=['one', 'normal', 'bulk'])\ndef test_shipping(qty, expected):\n    assert shipping_cost(qty) == expected",
        "usecase": "Wide parametrizations where the case meaning must be obvious in the failure report.",
        "category": "pytest",
    },
    {
        "id": 11,
        "title": "fixtures can be parametrized too",
        "definition": "Adding params to a fixture declaration makes pytest run each dependent test once per value, as if the fixture and the test were parametrized together. That gives matrix coverage — every test using the fixture sees every configuration — while the sharing logic stays confined to the fixture itself.",
        "example": "@pytest.fixture(params=['sqlite', 'postgres'])\ndef backend(request):\n    return connect(request.param)\n\ndef test_query(backend):\n    assert backend.query('select 1') == 1",
        "usecase": "Running one shared test body against multiple backends or configurations.",
        "category": "pytest",
    },
    {
        "id": 12,
        "title": "tmp_path gives a clean workspace",
        "definition": "The tmp_path fixture provides a unique, empty directory per test, removed automatically when the test finishes. Every test gets its own fresh directory, so file-based code is tested in isolation: no collision cleanup, no leftover files, and paths are written and read exactly like production directories.",
        "example": "def test_report_export(tmp_path):\n    out = tmp_path / 'report.csv'\n    export_reports(out)\n    assert out.exists()\n    assert out.read_text().startswith('id,')",
        "usecase": "Testing file writing, downloads, caches and exports against real filesystem behavior.",
        "category": "pytest",
    },
    {
        "id": 13,
        "title": "tmp_path_factory survives the session",
        "definition": "tmp_path_factory builds directories for session- and module-scoped fixtures that live for the whole duration of that scope, unlike the per-test tmp_path. Heavy resources needing a real location — large fixtures, build trees, downloaded corpora — keep their workspace through their lifetime, still rooted under pytest's managed tmpdir.",
        "example": "@pytest.fixture(scope='session')\ndef media_dir(tmp_path_factory):\n    return tmp_path_factory.mktemp('media')\n\ndef test_thumbnails(media_dir):\n    assert len(list(media_dir.iterdir())) > 0",
        "usecase": "Session-scoped caches and media trees that must exist for the whole run.",
        "category": "pytest",
    },
    {
        "id": 14,
        "title": "monkeypatch swaps behavior",
        "definition": "monkeypatch.setattr replaces any attribute, function or object for the duration of a test and restores it automatically afterwards, on every path including failures. That makes dependency fakes, clocks and environment values temporary instead of global: tests mutate behavior freely without leaking it into the next test.",
        "example": "def test_retry(monkeypatch):\n    calls = {'n': 0}\n    def flaky_get(url):\n        calls['n'] += 1\n        return None if calls['n'] < 3 else 'ok'\n    monkeypatch.setattr(service, 'fetch', flaky_get)\n    assert retry(service) == 'ok'",
        "usecase": "Stubbing network calls, time sources and external dependencies inside a single test.",
        "category": "pytest",
    },
    {
        "id": 15,
        "title": "monkeypatch sets env vars",
        "definition": "monkeypatch.setenv and monkeypatch.delenv set or remove environment variables for the test and restore the original values afterwards. Configuration read from os.environ at call time is therefore testable per case: feature flags, API keys and hostnames change without touching the real environment or other tests.",
        "example": "def test_api_url(monkeypatch):\n    monkeypatch.setenv('API_BASE', 'http://staging')\n    assert api_url() == 'http://staging/users'",
        "usecase": "Testing twelve-factor apps that read configuration from environment variables.",
        "category": "pytest",
    },
    {
        "id": 16,
        "title": "capsys captures output",
        "definition": "The capsys fixture captures everything a test prints or writes through sys.stdout and sys.stderr, and exposes it via capsys.readouterr(). Output is asserted as data instead of polluting the report, and prints that escape the capture or appear unexpectedly become failing checks.",
        "example": "def test_greet(capsys):\n    greet('Ada')\n    captured = capsys.readouterr()\n    assert captured.out == 'Hello, Ada!\\n'\n    assert captured.err == ''",
        "usecase": "Testing CLI tools and greeting flows by asserting on their printed output.",
        "category": "pytest",
    },
    {
        "id": 17,
        "title": "capfd captures at the OS level",
        "definition": "capfd captures output at the file-descriptor level, not just the sys.stdout streams, so even C extensions, subprocesses and libraries that bypass Python print land in the capture. It exposes the same readouterr interface as capsys but sees everything that reaches file descriptors one and two.",
        "example": "def test_native_tool(capfd):\n    run_native_tool()          # writes from C code\n    out, err = capfd.readouterr()\n    assert 'error' not in err",
        "usecase": "Capturing output from subprocesses and binary libraries that print outside Python.",
        "category": "pytest",
    },
    {
        "id": 18,
        "title": "caplog reads the logs",
        "definition": "The caplog fixture captures every record emitted by the logging module under any logger name, and tests assert on levels, records and messages with caplog.records and caplog.at_level. Silent failure paths become testable: raise the level, perform the action, then check exactly what was logged.",
        "example": "import logging\n\ndef test_empty_cart(caplog):\n    with caplog.at_level(logging.WARNING):\n        checkout(total=0)\n    assert 'empty cart' in caplog.text",
        "usecase": "Asserting on the log trail of error paths and background jobs.",
        "category": "pytest",
    },
    {
        "id": 19,
        "title": "raises expects the exception",
        "definition": "The pytest.raises context manager both runs a block and asserts that a specific exception was raised inside it, failing the test if none appears or if the type differs. Exceptions become assertable behavior instead of accidents, and the caught exception value is available for further checks inside the block.",
        "example": "import pytest\n\ndef test_divide_by_zero():\n    with pytest.raises(ZeroDivisionError):\n        compute(1, 0)",
        "usecase": "Contract tests for validated input — divisions, lookups, parsing and type errors.",
        "category": "pytest",
    },
    {
        "id": 20,
        "title": "match pins the message",
        "definition": "Passing match= to raises additionally asserts that the exception message matches the given regular expression, so not only the type but the reason is verified. Similar errors raised for different causes stop passing, and the same match argument works with pytest.warns for warnings that carry payloads.",
        "example": "import pytest\n\ndef test_negative_price():\n    with pytest.raises(ValueError, match='price.*positive'):\n        create_item(price=-5)",
        "usecase": "Tightening error-handling tests to the specific messages users and systems see.",
        "category": "pytest",
    },
    {
        "id": 21,
        "title": "warns checks the warnings",
        "definition": "The pytest.warns context manager asserts that executing a block produces a warning of a given category, for example pytest.warns(DeprecationWarning). Warnings become part of the contract — proving that a legacy path still alerts its callers — while recwarn gives raw typed access to every warning emitted.",
        "example": "import pytest\n\ndef test_legacy_call():\n    with pytest.warns(DeprecationWarning):\n        legacy_api()",
        "usecase": "Pinning deprecations and resource warnings before migrating callers.",
        "category": "pytest",
    },
    {
        "id": 22,
        "title": "approx compares floats fairly",
        "definition": "pytest.approx wraps expected values so comparisons ignore tiny floating point noise: assert 0.3 == pytest.approx(0.1 + 0.2) passes the way humans expect. It applies to scalars, lists, dicts and sets, with rel and abs tolerances tunable per case, replacing brittle exact equality on computed numbers.",
        "example": "import pytest\n\ndef test_tax():\n    assert tax(100.0) == pytest.approx(19.0, abs=0.01)\n    assert [0.1, 0.2] == pytest.approx([0.3, 0.4], rel=1e-3)",
        "usecase": "Financial math, physics and anything with floating point accumulation.",
        "category": "pytest",
    },
    {
        "id": 23,
        "title": "marks organize the suite",
        "definition": "Custom marks like @pytest.mark.slow tag tests, and the -m flag selects them: pytest -m 'not slow' runs everything else. Marks also carry conditions and metadata that plugins read, turning the suite into a queryable collection rather than a flat run-everything wall.",
        "example": "import pytest\n\n@pytest.mark.slow\ndef test_full_export():\n    export_all()      # skipped unless -m slow is requested",
        "usecase": "Separating fast unit loops from slow integration runs in CI stages.",
        "category": "pytest",
    },
    {
        "id": 24,
        "title": "skipping is a decision",
        "definition": "pytest.mark.skip marks a test as intentionally not executed, while skipif adds a condition evaluated at runtime, both reporting the skip distinctly from a failure. A suite that documents why certain tests do not run here — missing dependency, wrong platform — reads clearly, since skips are neither red nor green.",
        "example": "import sys\nimport pytest\n\n@pytest.mark.skipif(sys.version_info < (3, 11), reason='needs tomllib')\ndef test_config_load():\n    assert load_config('pyproject.toml')['name'] == 'app'",
        "usecase": "Version- and platform-dependent tests that exit cleanly elsewhere.",
        "category": "pytest",
    },
    {
        "id": 25,
        "title": "xfail documents known failures",
        "definition": "pytest.mark.xfail marks a test as expected to fail: it reports as xfailed and never goes red, and if it unexpectedly passes it shows xpass so the mark gets removed. Known bugs stay visible in the run instead of being deleted or silenced, and reason= explains why the failure is expected.",
        "example": "import pytest\n\n@pytest.mark.xfail(reason='upstream bug #1234, fixed in 2.1')\ndef test_legacy_encoding():\n    assert encode('cafe') == 'caf\xe9'",
        "usecase": "Tracking known-breaking conditions while a fix or workaround is pending.",
        "category": "pytest",
    },
    {
        "id": 26,
        "title": "autouse fixtures apply silently",
        "definition": "A fixture with autouse=True runs for every test in its scope without being named, perfect for ambient setup every test needs — environment corners, caches, logging isolation. The fixture signature still accepts other fixtures, so autouse setup can be scoped to a module through conftest or parametrized like any fixture.",
        "example": "import logging\nimport pytest\n\n@pytest.fixture(autouse=True)\ndef quiet_logging():\n    logging.disable(logging.CRITICAL)\n    yield\n    logging.disable(logging.NOTSET)",
        "usecase": "Global but controlled preconditions: set and restore state around each test.",
        "category": "pytest",
    },
    {
        "id": 27,
        "title": "fixture factories build variants",
        "definition": "Instead of returning a single object, a fixture can return a factory function, and each test calls that function with its own arguments to build variants. That pattern gives one setup location with arbitrary per-test data — users with different roles, orders with different statuses — without parametrizing the whole fixture.",
        "example": "@pytest.fixture\ndef make_user(db):\n    def _make(role='viewer', active=True):\n        return db.create_user(role=role, active=active)\n    return _make\n\ndef test_admin_only(make_user):\n    admin = make_user(role='admin')\n    assert can_delete(admin)",
        "usecase": "Combinatorial object construction for permission and workflow tests.",
        "category": "pytest",
    },
    {
        "id": 28,
        "title": "indirect feeds fixture parameters",
        "definition": "With indirect=True, parametrize arguments go to the fixture instead of the test, so one fixture is built once per parameter while the test body stays single. That is how test cases vary the setup itself — backend, locale, user tier — instead of only varying the plain function inputs.",
        "example": "@pytest.fixture\ndef backend(request):\n    return connect(request.param)\n\n@pytest.mark.parametrize('backend', ['sqlite', 'postgres'], indirect=True)\ndef test_query(backend):\n    assert backend.query('select 1') == 1",
        "usecase": "Same assertions against different tested configurations.",
        "category": "pytest",
    },
    {
        "id": 29,
        "title": "pytest.ini configures the run",
        "definition": "The pytest.ini file holds suite-wide settings in one place: testpaths, addopts for always-on flags, markers registered to silence warnings, filterwarnings policies and custom ini options for plugins. Configuration travels with the project, so every developer and CI machine starts from identical command lines.",
        "example": "# pytest.ini\n[pytest]\ntestpaths = tests\naddopts = -q --strict-markers\nmarkers =\n    slow: long running\n    smoke: quick sanity\nfilterwarnings = error",
        "usecase": "Reproducible behavior for whole teams and CI pipelines from a single file.",
        "category": "pytest",
    },
    {
        "id": 30,
        "title": "plugins extend pytest",
        "definition": "The pytest ecosystem is a plugin system: pytest-cov for coverage, pytest-xdist for parallel runs, pytest-django and pytest-asyncio for frameworks, each hooking in without changing the suite. Installations stay per-project via requirements, and plugins compose, so batteries are added exactly where they are needed.",
        "example": "# terminal\npip install pytest-xdist pytest-cov\npytest -n 4 --cov=src --cov-report=term-missing",
        "usecase": "Parallel execution, coverage gates and framework integrations without custom machinery.",
        "category": "pytest",
    },
    {
        "id": 31,
        "title": "-k filters tests by name",
        "definition": "The -k expression selects tests by matching substrings against their names and marks: pytest -k 'user or auth' runs every test whose name contains either word, and 'not slow' excludes a marker. That turns the suite into a searchable index for daily development loops.",
        "example": "# terminal\npytest -k 'report and not slow' tests/",
        "usecase": "Focusing on the subsystem being edited while the rest of the suite stays available.",
        "category": "pytest",
    },
    {
        "id": 32,
        "title": "-x fails fast",
        "definition": "The -x flag stops the whole run at the first failing test, while --maxfail=N stops after N failures. Long suites shorten their feedback loop on breakage: fix the first failure, rerun, discover the next — instead of burning the entire suite on the same root cause.",
        "example": "# terminal\npytest -x tests/           # halt at the first failure\npytest --maxfail=3 tests/  # halt after three",
        "usecase": "CI inner loops where one root cause poisons many follow-up tests.",
        "category": "pytest",
    },
    {
        "id": 33,
        "title": "--lf reruns last failures",
        "definition": "The --lf flag reruns only the tests that failed in the previous session and skips everything else; if the last run was fully green, the whole suite runs normally. The bookkeeping lives in pytest's cache directory, so the flag works with zero configuration.",
        "example": "# terminal\npytest --lf          # only the failures from the last run",
        "usecase": "Iterating on a fix until green, then running the whole suite once.",
        "category": "pytest",
    },
    {
        "id": 34,
        "title": "--ff fails first, then the rest",
        "definition": "The --ff flag runs the previously failed tests first, then continues with the remaining collection. CI and nightly runs get failed-fast feedback while still verifying everything, and the failure history ordering makes broken tests visible at the very top of the output.",
        "example": "# terminal\npytest --ff",
        "usecase": "CI runs where broken tests must appear at the top of the log.",
        "category": "pytest",
    },
    {
        "id": 35,
        "title": "--pdb drops into the debugger",
        "definition": "Running with --pdb drops into a pdb debugger right where a test fails, with fixtures and locals still on the stack, and --pdb --trace starts the debugger at the very beginning of each test. Debugger sessions are interactive but scriptable, turning reproduction into direct inspection.",
        "example": "# terminal\npytest --pdb tests/test_cart.py",
        "usecase": "Investigating a failure interactively instead of adding prints and rerunning.",
        "category": "pytest",
    },
    {
        "id": 36,
        "title": "--durations finds slow tests",
        "definition": "The --durations=N flag prints the N slowest tests at the end of the run with their exact timings, and --durations=0 lists every test's duration. Profiling the suite this way spots unexpected regressions and candidates for scope changes before they silently blow up CI budgets.",
        "example": "# terminal\npytest --durations=10",
        "usecase": "Finding the tests that actually deserve the profiling session.",
        "category": "pytest",
    },
    {
        "id": 37,
        "title": "doctests test the examples",
        "definition": "pytest runs doctests from docstrings and markdown with --doctest-modules and --doctest-glob, executing each example as a test: the triple-quote input lines run and their expected outputs are compared. Documentation examples become executable contracts, so snippets in READMEs and docstrings cannot drift from the code they describe.",
        "example": "# terminal\npytest --doctest-modules src/ --doctest-glob='*.md'",
        "usecase": "Keeping usage examples in docs honest without writing parallel test code.",
        "category": "pytest",
    },
    {
        "id": 38,
        "title": "coverage measures the work",
        "definition": "The pytest-cov plugin measures which lines the suite executes: pytest --cov=src prints coverage per module and fails with --cov-fail-under when a threshold is missed. Coverage quantifies the test suite's reach, and the report makes gaps visible before a release ships untested paths.",
        "example": "# terminal\npytest --cov=src --cov-report=term-missing --cov-fail-under=90",
        "usecase": "Quality gates in CI and visibility into untouched code paths.",
        "category": "pytest",
    },
    {
        "id": 39,
        "title": "hypothesis finds the edge cases",
        "definition": "Hypothesis generates hundreds of inputs per property test and searches for the smallest example that fails, using given and strategies from the hypothesis package. Instead of hand-picked cases, strategies describe whole input spaces — integers, lists, JSON — and the library reports minimal single reproductions.",
        "example": "from hypothesis import given, strategies as st\n\n@given(st.integers(), st.integers())\ndef test_commutative(a, b):\n    assert add(a, b) == add(b, a)",
        "usecase": "Finding bugs in functions whose correct input space is too large to enumerate.",
        "category": "pytest",
    },
    {
        "id": 40,
        "title": "async tests await with asyncio",
        "definition": "The pytest-asyncio plugin runs coroutine tests: functions decorated with @pytest.mark.asyncio are awaited by the event loop instead of being skipped, and async fixtures work the same way. Async integration tests, database calls and API clients then behave like their production code while still using fixtures, marks and parametrization.",
        "example": "import pytest\n\n@pytest.mark.asyncio\nasync def test_fetch():\n    async with AsyncClient() as client:\n        r = await client.get('http://testserver/ping')\n    assert r.status_code == 200",
        "usecase": "Testing async web handlers and clients with the same fixture machinery.",
        "category": "pytest",
    },
    {
        "id": 41,
        "title": "custom markers need registration",
        "definition": "New marker names should be declared in pytest.ini under markers and validated with --strict-markers on CI, so typos in marks become errors instead of silently mis-selected tests. Registration also documents the suite's vocabulary — what slow, smoke and perf mean in this project.",
        "example": "# pytest.ini\nmarkers =\n    slow: long running\n    smoke: quick sanity\n    perf: benchmarks\n# terminal\npytest --strict-markers",
        "usecase": "Keeping mark names typo-proof when many developers add tags.",
        "category": "pytest",
    },
    {
        "id": 42,
        "title": "cache remembers your runs",
        "definition": "pytest records cross-run state in .pytest_cache: which tests failed last time, how long each one took, and custom values stored through the cache fixture. --lf, --ff and --durations all read it, and pytest -p no:cacheprovider or --cache-clear throws that state away when it should not persist.",
        "example": "# terminal\npytest -p no:cacheprovider   # disable the cache writer\npytest --cache-clear         # reset failure memory",
        "usecase": "Failure memory between local iterations without any external storage.",
        "category": "pytest",
    },
    {
        "id": 43,
        "title": "parametrized combinations multiply",
        "definition": "Stacking several @pytest.mark.parametrize decorators produces the Cartesian product of the lists — every argument combination runs as its own case. Combinatorial coverage over input pairs and setup matrices comes from plain composition, and failures pinpoint the exact combination that broke.",
        "example": "@pytest.mark.parametrize('user', ['viewer', 'admin'])\n@pytest.mark.parametrize('action', ['read', 'write'])\ndef test_permissions(user, action):\n    assert can(user, action) == ALLOWED[(user, action)]",
        "usecase": "Permission matrices, feature-flag crossings and format combinations.",
        "category": "pytest",
    },
    {
        "id": 44,
        "title": "exit codes tell the outcome",
        "definition": "CI scripts branch on pytest's exit code: 0 all passed, 1 some failed, 2 interrupted, 3 internal error, 4 usage error, 5 no tests collected. Wrapping pytest in shell scripts and tools relies on these stable codes, and 5 especially catches suites that silently collect nothing at all.",
        "example": "# terminal\npytest . && echo 'green' || echo \"red (exit $?)\"",
        "usecase": "CI pipelines and wrapper scripts that must react to the true suite outcome.",
        "category": "pytest",
    },
    {
        "id": 45,
        "title": "select tests by node id",
        "definition": "Every collected test has a unique node id — path::class::function — and passing one to pytest runs just that test, with partial filters like test_filters.py::test_by_name. Exact reproduction of one failing case comes from one node id copied from the CI log, and the ids remain valid across runs.",
        "example": "# terminal\npytest tests/test_filters.py::test_by_name\npytest tests/test_filters.py::test_by_name::['bulk']",
        "usecase": "Re-running exactly the failing case from the CI report.",
        "category": "pytest",
    },
    {
        "id": 46,
        "title": "conditions pick the skips",
        "definition": "skipif takes any boolean expression evaluated at collection time, so platform flags, interpreter versions and environment variables decide per test whether it runs. Helpers like pytest.importorskip extend the same idea: skip the file when an optional dependency is absent, with the reason shown in the report.",
        "example": "import sys\nimport pytest\n\n@pytest.mark.skipif(sys.platform == 'win32', reason='POSIX sockets only')\ndef test_unix_socket():\n    open_socket('/run/app.sock')",
        "usecase": "Cross-platform suites that adapt to the machine instead of failing on it.",
        "category": "pytest",
    },
    {
        "id": 47,
        "title": "filterwarnings quiet the noise",
        "definition": "The filterwarnings ini option and -W flag control warning handling suite-wide: error turns warnings into failures, ignore silences known noise, always prints them. Warning policies are configured once and overridden per case with @pytest.mark.filterwarnings, keeping deprecation smoke from drowning real reports.",
        "example": "# pytest.ini\nfilterwarnings =\n    error\n    ignore:.*numpy.*:DeprecationWarning",
        "usecase": "Making deprecations loud in development while pinning known third-party noise.",
        "category": "pytest",
    },
    {
        "id": 48,
        "title": "one failure per test",
        "definition": "A test should assert one logical fact, because the first failed assert stops the function and hides everything after it — a loop full of asserts reports only the first broken element. Splitting cases into parametrized rows lets every input fail individually, which is faster to fix and safer than a wall of asserts.",
        "example": "@pytest.mark.parametrize('email', ['a@b.co', 'x@y.io'])\ndef test_valid_emails(email):\n    assert validate(email) is True",
        "usecase": "Granular failure reporting on data-validated code paths.",
        "category": "pytest",
    },
    {
        "id": 49,
        "title": "suite layout mirrors the code",
        "definition": "A tests/ directory that mirrors the package under test — tests/api/, tests/models/ — keeps large suites navigable, and per-area conftest files scope shared fixtures next to their consumers. pytest's default discovery and testpaths then find everything without import tricks or runner configuration.",
        "example": "src/app           tests/app\n├── models.py      ├── test_models.py\n└── api/           └── api/test_handlers.py",
        "usecase": "Growable suites where the mapping of tests to modules stays obvious.",
        "category": "pytest",
    },
    {
        "id": 50,
        "title": "tracebacks report the details",
        "definition": "Traceback verbosity is a command-line choice: --tb=short keeps failures to the relevant frames, --tb=long shows everything, -v prints each collected test by name, and --showlocals dumps local variable values at the point of failure. Matching output to the moment — readable blame on CI, deep dumps while debugging — costs nothing.",
        "example": "# terminal\npytest --tb=short\npytest -v --showlocals",
        "usecase": "Less noise in CI logs, more context while debugging locally.",
        "category": "pytest",
    },
]